
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  attachments: 'attachments',
  colleges: 'colleges',
  delegations: 'delegations',
  departments: 'departments',
  form_templates: 'form_templates',
  notifications: 'notifications',
  request_actions: 'request_actions',
  request_types: 'request_types',
  requests: 'requests',
  roles: 'roles',
  users: 'users',
  workflow_steps: 'workflow_steps',
  workflows: 'workflows'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "attachments" | "colleges" | "delegations" | "departments" | "form_templates" | "notifications" | "request_actions" | "request_types" | "requests" | "roles" | "users" | "workflow_steps" | "workflows"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    attachments: {
      payload: Prisma.$attachmentsPayload<ExtArgs>
      fields: Prisma.attachmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.attachmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.attachmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        findFirst: {
          args: Prisma.attachmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.attachmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        findMany: {
          args: Prisma.attachmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>[]
        }
        create: {
          args: Prisma.attachmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        createMany: {
          args: Prisma.attachmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.attachmentsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>[]
        }
        delete: {
          args: Prisma.attachmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        update: {
          args: Prisma.attachmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        deleteMany: {
          args: Prisma.attachmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.attachmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.attachmentsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>[]
        }
        upsert: {
          args: Prisma.attachmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$attachmentsPayload>
        }
        aggregate: {
          args: Prisma.AttachmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAttachments>
        }
        groupBy: {
          args: Prisma.attachmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttachmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.attachmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AttachmentsCountAggregateOutputType> | number
        }
      }
    }
    colleges: {
      payload: Prisma.$collegesPayload<ExtArgs>
      fields: Prisma.collegesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.collegesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.collegesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        findFirst: {
          args: Prisma.collegesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.collegesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        findMany: {
          args: Prisma.collegesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>[]
        }
        create: {
          args: Prisma.collegesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        createMany: {
          args: Prisma.collegesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.collegesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>[]
        }
        delete: {
          args: Prisma.collegesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        update: {
          args: Prisma.collegesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        deleteMany: {
          args: Prisma.collegesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.collegesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.collegesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>[]
        }
        upsert: {
          args: Prisma.collegesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$collegesPayload>
        }
        aggregate: {
          args: Prisma.CollegesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateColleges>
        }
        groupBy: {
          args: Prisma.collegesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CollegesGroupByOutputType>[]
        }
        count: {
          args: Prisma.collegesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CollegesCountAggregateOutputType> | number
        }
      }
    }
    delegations: {
      payload: Prisma.$delegationsPayload<ExtArgs>
      fields: Prisma.delegationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.delegationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.delegationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        findFirst: {
          args: Prisma.delegationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.delegationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        findMany: {
          args: Prisma.delegationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>[]
        }
        create: {
          args: Prisma.delegationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        createMany: {
          args: Prisma.delegationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.delegationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>[]
        }
        delete: {
          args: Prisma.delegationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        update: {
          args: Prisma.delegationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        deleteMany: {
          args: Prisma.delegationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.delegationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.delegationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>[]
        }
        upsert: {
          args: Prisma.delegationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$delegationsPayload>
        }
        aggregate: {
          args: Prisma.DelegationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDelegations>
        }
        groupBy: {
          args: Prisma.delegationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DelegationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.delegationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DelegationsCountAggregateOutputType> | number
        }
      }
    }
    departments: {
      payload: Prisma.$departmentsPayload<ExtArgs>
      fields: Prisma.departmentsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.departmentsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.departmentsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        findFirst: {
          args: Prisma.departmentsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.departmentsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        findMany: {
          args: Prisma.departmentsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>[]
        }
        create: {
          args: Prisma.departmentsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        createMany: {
          args: Prisma.departmentsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.departmentsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>[]
        }
        delete: {
          args: Prisma.departmentsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        update: {
          args: Prisma.departmentsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        deleteMany: {
          args: Prisma.departmentsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.departmentsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.departmentsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>[]
        }
        upsert: {
          args: Prisma.departmentsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$departmentsPayload>
        }
        aggregate: {
          args: Prisma.DepartmentsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDepartments>
        }
        groupBy: {
          args: Prisma.departmentsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsGroupByOutputType>[]
        }
        count: {
          args: Prisma.departmentsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DepartmentsCountAggregateOutputType> | number
        }
      }
    }
    form_templates: {
      payload: Prisma.$form_templatesPayload<ExtArgs>
      fields: Prisma.form_templatesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.form_templatesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.form_templatesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        findFirst: {
          args: Prisma.form_templatesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.form_templatesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        findMany: {
          args: Prisma.form_templatesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>[]
        }
        create: {
          args: Prisma.form_templatesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        createMany: {
          args: Prisma.form_templatesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.form_templatesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>[]
        }
        delete: {
          args: Prisma.form_templatesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        update: {
          args: Prisma.form_templatesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        deleteMany: {
          args: Prisma.form_templatesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.form_templatesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.form_templatesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>[]
        }
        upsert: {
          args: Prisma.form_templatesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$form_templatesPayload>
        }
        aggregate: {
          args: Prisma.Form_templatesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateForm_templates>
        }
        groupBy: {
          args: Prisma.form_templatesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Form_templatesGroupByOutputType>[]
        }
        count: {
          args: Prisma.form_templatesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Form_templatesCountAggregateOutputType> | number
        }
      }
    }
    notifications: {
      payload: Prisma.$notificationsPayload<ExtArgs>
      fields: Prisma.notificationsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.notificationsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.notificationsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        findFirst: {
          args: Prisma.notificationsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.notificationsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        findMany: {
          args: Prisma.notificationsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>[]
        }
        create: {
          args: Prisma.notificationsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        createMany: {
          args: Prisma.notificationsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.notificationsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>[]
        }
        delete: {
          args: Prisma.notificationsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        update: {
          args: Prisma.notificationsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        deleteMany: {
          args: Prisma.notificationsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.notificationsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.notificationsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>[]
        }
        upsert: {
          args: Prisma.notificationsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$notificationsPayload>
        }
        aggregate: {
          args: Prisma.NotificationsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNotifications>
        }
        groupBy: {
          args: Prisma.notificationsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationsGroupByOutputType>[]
        }
        count: {
          args: Prisma.notificationsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NotificationsCountAggregateOutputType> | number
        }
      }
    }
    request_actions: {
      payload: Prisma.$request_actionsPayload<ExtArgs>
      fields: Prisma.request_actionsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.request_actionsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.request_actionsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        findFirst: {
          args: Prisma.request_actionsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.request_actionsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        findMany: {
          args: Prisma.request_actionsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>[]
        }
        create: {
          args: Prisma.request_actionsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        createMany: {
          args: Prisma.request_actionsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.request_actionsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>[]
        }
        delete: {
          args: Prisma.request_actionsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        update: {
          args: Prisma.request_actionsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        deleteMany: {
          args: Prisma.request_actionsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.request_actionsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.request_actionsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>[]
        }
        upsert: {
          args: Prisma.request_actionsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_actionsPayload>
        }
        aggregate: {
          args: Prisma.Request_actionsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRequest_actions>
        }
        groupBy: {
          args: Prisma.request_actionsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Request_actionsGroupByOutputType>[]
        }
        count: {
          args: Prisma.request_actionsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Request_actionsCountAggregateOutputType> | number
        }
      }
    }
    request_types: {
      payload: Prisma.$request_typesPayload<ExtArgs>
      fields: Prisma.request_typesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.request_typesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.request_typesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        findFirst: {
          args: Prisma.request_typesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.request_typesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        findMany: {
          args: Prisma.request_typesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>[]
        }
        create: {
          args: Prisma.request_typesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        createMany: {
          args: Prisma.request_typesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.request_typesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>[]
        }
        delete: {
          args: Prisma.request_typesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        update: {
          args: Prisma.request_typesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        deleteMany: {
          args: Prisma.request_typesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.request_typesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.request_typesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>[]
        }
        upsert: {
          args: Prisma.request_typesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$request_typesPayload>
        }
        aggregate: {
          args: Prisma.Request_typesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRequest_types>
        }
        groupBy: {
          args: Prisma.request_typesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Request_typesGroupByOutputType>[]
        }
        count: {
          args: Prisma.request_typesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Request_typesCountAggregateOutputType> | number
        }
      }
    }
    requests: {
      payload: Prisma.$requestsPayload<ExtArgs>
      fields: Prisma.requestsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.requestsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.requestsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        findFirst: {
          args: Prisma.requestsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.requestsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        findMany: {
          args: Prisma.requestsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>[]
        }
        create: {
          args: Prisma.requestsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        createMany: {
          args: Prisma.requestsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.requestsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>[]
        }
        delete: {
          args: Prisma.requestsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        update: {
          args: Prisma.requestsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        deleteMany: {
          args: Prisma.requestsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.requestsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.requestsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>[]
        }
        upsert: {
          args: Prisma.requestsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$requestsPayload>
        }
        aggregate: {
          args: Prisma.RequestsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRequests>
        }
        groupBy: {
          args: Prisma.requestsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RequestsGroupByOutputType>[]
        }
        count: {
          args: Prisma.requestsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RequestsCountAggregateOutputType> | number
        }
      }
    }
    roles: {
      payload: Prisma.$rolesPayload<ExtArgs>
      fields: Prisma.rolesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.rolesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.rolesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        findFirst: {
          args: Prisma.rolesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.rolesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        findMany: {
          args: Prisma.rolesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>[]
        }
        create: {
          args: Prisma.rolesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        createMany: {
          args: Prisma.rolesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.rolesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>[]
        }
        delete: {
          args: Prisma.rolesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        update: {
          args: Prisma.rolesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        deleteMany: {
          args: Prisma.rolesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.rolesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.rolesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>[]
        }
        upsert: {
          args: Prisma.rolesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$rolesPayload>
        }
        aggregate: {
          args: Prisma.RolesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRoles>
        }
        groupBy: {
          args: Prisma.rolesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesGroupByOutputType>[]
        }
        count: {
          args: Prisma.rolesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RolesCountAggregateOutputType> | number
        }
      }
    }
    users: {
      payload: Prisma.$usersPayload<ExtArgs>
      fields: Prisma.usersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.usersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.usersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        findFirst: {
          args: Prisma.usersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.usersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        findMany: {
          args: Prisma.usersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        create: {
          args: Prisma.usersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        createMany: {
          args: Prisma.usersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.usersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        delete: {
          args: Prisma.usersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        update: {
          args: Prisma.usersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        deleteMany: {
          args: Prisma.usersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.usersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.usersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        upsert: {
          args: Prisma.usersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.usersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.usersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
    workflow_steps: {
      payload: Prisma.$workflow_stepsPayload<ExtArgs>
      fields: Prisma.workflow_stepsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.workflow_stepsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.workflow_stepsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        findFirst: {
          args: Prisma.workflow_stepsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.workflow_stepsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        findMany: {
          args: Prisma.workflow_stepsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>[]
        }
        create: {
          args: Prisma.workflow_stepsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        createMany: {
          args: Prisma.workflow_stepsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.workflow_stepsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>[]
        }
        delete: {
          args: Prisma.workflow_stepsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        update: {
          args: Prisma.workflow_stepsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        deleteMany: {
          args: Prisma.workflow_stepsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.workflow_stepsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.workflow_stepsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>[]
        }
        upsert: {
          args: Prisma.workflow_stepsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflow_stepsPayload>
        }
        aggregate: {
          args: Prisma.Workflow_stepsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorkflow_steps>
        }
        groupBy: {
          args: Prisma.workflow_stepsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Workflow_stepsGroupByOutputType>[]
        }
        count: {
          args: Prisma.workflow_stepsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Workflow_stepsCountAggregateOutputType> | number
        }
      }
    }
    workflows: {
      payload: Prisma.$workflowsPayload<ExtArgs>
      fields: Prisma.workflowsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.workflowsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.workflowsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        findFirst: {
          args: Prisma.workflowsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.workflowsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        findMany: {
          args: Prisma.workflowsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>[]
        }
        create: {
          args: Prisma.workflowsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        createMany: {
          args: Prisma.workflowsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.workflowsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>[]
        }
        delete: {
          args: Prisma.workflowsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        update: {
          args: Prisma.workflowsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        deleteMany: {
          args: Prisma.workflowsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.workflowsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.workflowsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>[]
        }
        upsert: {
          args: Prisma.workflowsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$workflowsPayload>
        }
        aggregate: {
          args: Prisma.WorkflowsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorkflows>
        }
        groupBy: {
          args: Prisma.workflowsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorkflowsGroupByOutputType>[]
        }
        count: {
          args: Prisma.workflowsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.WorkflowsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AttachmentsScalarFieldEnum = {
  file_id: 'file_id',
  request_id: 'request_id',
  uploader_id: 'uploader_id',
  storage_location: 'storage_location',
  file_type: 'file_type',
  uploaded_at: 'uploaded_at'
} as const

export type AttachmentsScalarFieldEnum = (typeof AttachmentsScalarFieldEnum)[keyof typeof AttachmentsScalarFieldEnum]


export const CollegesScalarFieldEnum = {
  college_id: 'college_id',
  name: 'name',
  dean_id: 'dean_id',
  created_at: 'created_at'
} as const

export type CollegesScalarFieldEnum = (typeof CollegesScalarFieldEnum)[keyof typeof CollegesScalarFieldEnum]


export const DelegationsScalarFieldEnum = {
  delegation_id: 'delegation_id',
  request_id: 'request_id',
  grantor_user_id: 'grantor_user_id',
  grantee_user_id: 'grantee_user_id',
  starts_at: 'starts_at',
  ends_at: 'ends_at',
  is_active: 'is_active'
} as const

export type DelegationsScalarFieldEnum = (typeof DelegationsScalarFieldEnum)[keyof typeof DelegationsScalarFieldEnum]


export const DepartmentsScalarFieldEnum = {
  department_id: 'department_id',
  dept_name: 'dept_name',
  college_id: 'college_id',
  manager_id: 'manager_id'
} as const

export type DepartmentsScalarFieldEnum = (typeof DepartmentsScalarFieldEnum)[keyof typeof DepartmentsScalarFieldEnum]


export const Form_templatesScalarFieldEnum = {
  form_id: 'form_id',
  request_type_id: 'request_type_id',
  name: 'name',
  audience_config: 'audience_config',
  is_active: 'is_active',
  schema: 'schema',
  created_at: 'created_at'
} as const

export type Form_templatesScalarFieldEnum = (typeof Form_templatesScalarFieldEnum)[keyof typeof Form_templatesScalarFieldEnum]


export const NotificationsScalarFieldEnum = {
  notification_id: 'notification_id',
  user_id: 'user_id',
  title: 'title',
  message: 'message',
  link: 'link',
  created_at: 'created_at'
} as const

export type NotificationsScalarFieldEnum = (typeof NotificationsScalarFieldEnum)[keyof typeof NotificationsScalarFieldEnum]


export const Request_actionsScalarFieldEnum = {
  action_id: 'action_id',
  request_id: 'request_id',
  actor_id: 'actor_id',
  step_id: 'step_id',
  action: 'action',
  comment: 'comment',
  created_at: 'created_at'
} as const

export type Request_actionsScalarFieldEnum = (typeof Request_actionsScalarFieldEnum)[keyof typeof Request_actionsScalarFieldEnum]


export const Request_typesScalarFieldEnum = {
  type_id: 'type_id',
  workflow_id: 'workflow_id',
  key: 'key',
  label: 'label'
} as const

export type Request_typesScalarFieldEnum = (typeof Request_typesScalarFieldEnum)[keyof typeof Request_typesScalarFieldEnum]


export const RequestsScalarFieldEnum = {
  request_id: 'request_id',
  reference_no: 'reference_no',
  requester_id: 'requester_id',
  form_id: 'form_id',
  current_step_id: 'current_step_id',
  status: 'status',
  submission_data: 'submission_data',
  submitted_at: 'submitted_at'
} as const

export type RequestsScalarFieldEnum = (typeof RequestsScalarFieldEnum)[keyof typeof RequestsScalarFieldEnum]


export const RolesScalarFieldEnum = {
  role_id: 'role_id',
  role_name: 'role_name',
  permissions: 'permissions'
} as const

export type RolesScalarFieldEnum = (typeof RolesScalarFieldEnum)[keyof typeof RolesScalarFieldEnum]


export const UsersScalarFieldEnum = {
  user_id: 'user_id',
  university_id: 'university_id',
  password_hash: 'password_hash',
  full_name: 'full_name',
  phone: 'phone',
  department_id: 'department_id',
  role_id: 'role_id',
  is_active: 'is_active',
  created_at: 'created_at'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const Workflow_stepsScalarFieldEnum = {
  step_id: 'step_id',
  workflow_id: 'workflow_id',
  order: 'order',
  name: 'name',
  approver_role_id: 'approver_role_id',
  sla_hours: 'sla_hours',
  is_final: 'is_final'
} as const

export type Workflow_stepsScalarFieldEnum = (typeof Workflow_stepsScalarFieldEnum)[keyof typeof Workflow_stepsScalarFieldEnum]


export const WorkflowsScalarFieldEnum = {
  workflow_id: 'workflow_id',
  name: 'name',
  is_active: 'is_active'
} as const

export type WorkflowsScalarFieldEnum = (typeof WorkflowsScalarFieldEnum)[keyof typeof WorkflowsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  attachments?: Prisma.attachmentsOmit
  colleges?: Prisma.collegesOmit
  delegations?: Prisma.delegationsOmit
  departments?: Prisma.departmentsOmit
  form_templates?: Prisma.form_templatesOmit
  notifications?: Prisma.notificationsOmit
  request_actions?: Prisma.request_actionsOmit
  request_types?: Prisma.request_typesOmit
  requests?: Prisma.requestsOmit
  roles?: Prisma.rolesOmit
  users?: Prisma.usersOmit
  workflow_steps?: Prisma.workflow_stepsOmit
  workflows?: Prisma.workflowsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

