
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `attachments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model attachments
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type attachmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$attachmentsPayload>

export type AggregateAttachments = {
  _count: AttachmentsCountAggregateOutputType | null
  _avg: AttachmentsAvgAggregateOutputType | null
  _sum: AttachmentsSumAggregateOutputType | null
  _min: AttachmentsMinAggregateOutputType | null
  _max: AttachmentsMaxAggregateOutputType | null
}

export type AttachmentsAvgAggregateOutputType = {
  file_id: number | null
  request_id: number | null
  uploader_id: number | null
}

export type AttachmentsSumAggregateOutputType = {
  file_id: number | null
  request_id: number | null
  uploader_id: number | null
}

export type AttachmentsMinAggregateOutputType = {
  file_id: number | null
  request_id: number | null
  uploader_id: number | null
  storage_location: string | null
  file_type: string | null
  uploaded_at: Date | null
}

export type AttachmentsMaxAggregateOutputType = {
  file_id: number | null
  request_id: number | null
  uploader_id: number | null
  storage_location: string | null
  file_type: string | null
  uploaded_at: Date | null
}

export type AttachmentsCountAggregateOutputType = {
  file_id: number
  request_id: number
  uploader_id: number
  storage_location: number
  file_type: number
  uploaded_at: number
  _all: number
}


export type AttachmentsAvgAggregateInputType = {
  file_id?: true
  request_id?: true
  uploader_id?: true
}

export type AttachmentsSumAggregateInputType = {
  file_id?: true
  request_id?: true
  uploader_id?: true
}

export type AttachmentsMinAggregateInputType = {
  file_id?: true
  request_id?: true
  uploader_id?: true
  storage_location?: true
  file_type?: true
  uploaded_at?: true
}

export type AttachmentsMaxAggregateInputType = {
  file_id?: true
  request_id?: true
  uploader_id?: true
  storage_location?: true
  file_type?: true
  uploaded_at?: true
}

export type AttachmentsCountAggregateInputType = {
  file_id?: true
  request_id?: true
  uploader_id?: true
  storage_location?: true
  file_type?: true
  uploaded_at?: true
  _all?: true
}

export type AttachmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which attachments to aggregate.
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of attachments to fetch.
   */
  orderBy?: Prisma.attachmentsOrderByWithRelationInput | Prisma.attachmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.attachmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned attachments
  **/
  _count?: true | AttachmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AttachmentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AttachmentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AttachmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AttachmentsMaxAggregateInputType
}

export type GetAttachmentsAggregateType<T extends AttachmentsAggregateArgs> = {
      [P in keyof T & keyof AggregateAttachments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAttachments[P]>
    : Prisma.GetScalarType<T[P], AggregateAttachments[P]>
}




export type attachmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.attachmentsWhereInput
  orderBy?: Prisma.attachmentsOrderByWithAggregationInput | Prisma.attachmentsOrderByWithAggregationInput[]
  by: Prisma.AttachmentsScalarFieldEnum[] | Prisma.AttachmentsScalarFieldEnum
  having?: Prisma.attachmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AttachmentsCountAggregateInputType | true
  _avg?: AttachmentsAvgAggregateInputType
  _sum?: AttachmentsSumAggregateInputType
  _min?: AttachmentsMinAggregateInputType
  _max?: AttachmentsMaxAggregateInputType
}

export type AttachmentsGroupByOutputType = {
  file_id: number
  request_id: number | null
  uploader_id: number | null
  storage_location: string | null
  file_type: string | null
  uploaded_at: Date | null
  _count: AttachmentsCountAggregateOutputType | null
  _avg: AttachmentsAvgAggregateOutputType | null
  _sum: AttachmentsSumAggregateOutputType | null
  _min: AttachmentsMinAggregateOutputType | null
  _max: AttachmentsMaxAggregateOutputType | null
}

type GetAttachmentsGroupByPayload<T extends attachmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AttachmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AttachmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AttachmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AttachmentsGroupByOutputType[P]>
      }
    >
  >



export type attachmentsWhereInput = {
  AND?: Prisma.attachmentsWhereInput | Prisma.attachmentsWhereInput[]
  OR?: Prisma.attachmentsWhereInput[]
  NOT?: Prisma.attachmentsWhereInput | Prisma.attachmentsWhereInput[]
  file_id?: Prisma.IntFilter<"attachments"> | number
  request_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  uploader_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  storage_location?: Prisma.StringNullableFilter<"attachments"> | string | null
  file_type?: Prisma.StringNullableFilter<"attachments"> | string | null
  uploaded_at?: Prisma.DateTimeNullableFilter<"attachments"> | Date | string | null
  requests?: Prisma.XOR<Prisma.RequestsNullableScalarRelationFilter, Prisma.requestsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}

export type attachmentsOrderByWithRelationInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrderInput | Prisma.SortOrder
  uploader_id?: Prisma.SortOrderInput | Prisma.SortOrder
  storage_location?: Prisma.SortOrderInput | Prisma.SortOrder
  file_type?: Prisma.SortOrderInput | Prisma.SortOrder
  uploaded_at?: Prisma.SortOrderInput | Prisma.SortOrder
  requests?: Prisma.requestsOrderByWithRelationInput
  users?: Prisma.usersOrderByWithRelationInput
}

export type attachmentsWhereUniqueInput = Prisma.AtLeast<{
  file_id?: number
  AND?: Prisma.attachmentsWhereInput | Prisma.attachmentsWhereInput[]
  OR?: Prisma.attachmentsWhereInput[]
  NOT?: Prisma.attachmentsWhereInput | Prisma.attachmentsWhereInput[]
  request_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  uploader_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  storage_location?: Prisma.StringNullableFilter<"attachments"> | string | null
  file_type?: Prisma.StringNullableFilter<"attachments"> | string | null
  uploaded_at?: Prisma.DateTimeNullableFilter<"attachments"> | Date | string | null
  requests?: Prisma.XOR<Prisma.RequestsNullableScalarRelationFilter, Prisma.requestsWhereInput> | null
  users?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
}, "file_id">

export type attachmentsOrderByWithAggregationInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrderInput | Prisma.SortOrder
  uploader_id?: Prisma.SortOrderInput | Prisma.SortOrder
  storage_location?: Prisma.SortOrderInput | Prisma.SortOrder
  file_type?: Prisma.SortOrderInput | Prisma.SortOrder
  uploaded_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.attachmentsCountOrderByAggregateInput
  _avg?: Prisma.attachmentsAvgOrderByAggregateInput
  _max?: Prisma.attachmentsMaxOrderByAggregateInput
  _min?: Prisma.attachmentsMinOrderByAggregateInput
  _sum?: Prisma.attachmentsSumOrderByAggregateInput
}

export type attachmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.attachmentsScalarWhereWithAggregatesInput | Prisma.attachmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.attachmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.attachmentsScalarWhereWithAggregatesInput | Prisma.attachmentsScalarWhereWithAggregatesInput[]
  file_id?: Prisma.IntWithAggregatesFilter<"attachments"> | number
  request_id?: Prisma.IntNullableWithAggregatesFilter<"attachments"> | number | null
  uploader_id?: Prisma.IntNullableWithAggregatesFilter<"attachments"> | number | null
  storage_location?: Prisma.StringNullableWithAggregatesFilter<"attachments"> | string | null
  file_type?: Prisma.StringNullableWithAggregatesFilter<"attachments"> | string | null
  uploaded_at?: Prisma.DateTimeNullableWithAggregatesFilter<"attachments"> | Date | string | null
}

export type attachmentsCreateInput = {
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
  requests?: Prisma.requestsCreateNestedOneWithoutAttachmentsInput
  users?: Prisma.usersCreateNestedOneWithoutAttachmentsInput
}

export type attachmentsUncheckedCreateInput = {
  file_id?: number
  request_id?: number | null
  uploader_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsUpdateInput = {
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  requests?: Prisma.requestsUpdateOneWithoutAttachmentsNestedInput
  users?: Prisma.usersUpdateOneWithoutAttachmentsNestedInput
}

export type attachmentsUncheckedUpdateInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploader_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsCreateManyInput = {
  file_id?: number
  request_id?: number | null
  uploader_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsUpdateManyMutationInput = {
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsUncheckedUpdateManyInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  uploader_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsCountOrderByAggregateInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  uploader_id?: Prisma.SortOrder
  storage_location?: Prisma.SortOrder
  file_type?: Prisma.SortOrder
  uploaded_at?: Prisma.SortOrder
}

export type attachmentsAvgOrderByAggregateInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  uploader_id?: Prisma.SortOrder
}

export type attachmentsMaxOrderByAggregateInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  uploader_id?: Prisma.SortOrder
  storage_location?: Prisma.SortOrder
  file_type?: Prisma.SortOrder
  uploaded_at?: Prisma.SortOrder
}

export type attachmentsMinOrderByAggregateInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  uploader_id?: Prisma.SortOrder
  storage_location?: Prisma.SortOrder
  file_type?: Prisma.SortOrder
  uploaded_at?: Prisma.SortOrder
}

export type attachmentsSumOrderByAggregateInput = {
  file_id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  uploader_id?: Prisma.SortOrder
}

export type AttachmentsListRelationFilter = {
  every?: Prisma.attachmentsWhereInput
  some?: Prisma.attachmentsWhereInput
  none?: Prisma.attachmentsWhereInput
}

export type attachmentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type attachmentsCreateNestedManyWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput> | Prisma.attachmentsCreateWithoutRequestsInput[] | Prisma.attachmentsUncheckedCreateWithoutRequestsInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutRequestsInput | Prisma.attachmentsCreateOrConnectWithoutRequestsInput[]
  createMany?: Prisma.attachmentsCreateManyRequestsInputEnvelope
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
}

export type attachmentsUncheckedCreateNestedManyWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput> | Prisma.attachmentsCreateWithoutRequestsInput[] | Prisma.attachmentsUncheckedCreateWithoutRequestsInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutRequestsInput | Prisma.attachmentsCreateOrConnectWithoutRequestsInput[]
  createMany?: Prisma.attachmentsCreateManyRequestsInputEnvelope
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
}

export type attachmentsUpdateManyWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput> | Prisma.attachmentsCreateWithoutRequestsInput[] | Prisma.attachmentsUncheckedCreateWithoutRequestsInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutRequestsInput | Prisma.attachmentsCreateOrConnectWithoutRequestsInput[]
  upsert?: Prisma.attachmentsUpsertWithWhereUniqueWithoutRequestsInput | Prisma.attachmentsUpsertWithWhereUniqueWithoutRequestsInput[]
  createMany?: Prisma.attachmentsCreateManyRequestsInputEnvelope
  set?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  disconnect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  delete?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  update?: Prisma.attachmentsUpdateWithWhereUniqueWithoutRequestsInput | Prisma.attachmentsUpdateWithWhereUniqueWithoutRequestsInput[]
  updateMany?: Prisma.attachmentsUpdateManyWithWhereWithoutRequestsInput | Prisma.attachmentsUpdateManyWithWhereWithoutRequestsInput[]
  deleteMany?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
}

export type attachmentsUncheckedUpdateManyWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput> | Prisma.attachmentsCreateWithoutRequestsInput[] | Prisma.attachmentsUncheckedCreateWithoutRequestsInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutRequestsInput | Prisma.attachmentsCreateOrConnectWithoutRequestsInput[]
  upsert?: Prisma.attachmentsUpsertWithWhereUniqueWithoutRequestsInput | Prisma.attachmentsUpsertWithWhereUniqueWithoutRequestsInput[]
  createMany?: Prisma.attachmentsCreateManyRequestsInputEnvelope
  set?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  disconnect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  delete?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  update?: Prisma.attachmentsUpdateWithWhereUniqueWithoutRequestsInput | Prisma.attachmentsUpdateWithWhereUniqueWithoutRequestsInput[]
  updateMany?: Prisma.attachmentsUpdateManyWithWhereWithoutRequestsInput | Prisma.attachmentsUpdateManyWithWhereWithoutRequestsInput[]
  deleteMany?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
}

export type attachmentsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput> | Prisma.attachmentsCreateWithoutUsersInput[] | Prisma.attachmentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutUsersInput | Prisma.attachmentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.attachmentsCreateManyUsersInputEnvelope
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
}

export type attachmentsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput> | Prisma.attachmentsCreateWithoutUsersInput[] | Prisma.attachmentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutUsersInput | Prisma.attachmentsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.attachmentsCreateManyUsersInputEnvelope
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
}

export type attachmentsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput> | Prisma.attachmentsCreateWithoutUsersInput[] | Prisma.attachmentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutUsersInput | Prisma.attachmentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.attachmentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.attachmentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.attachmentsCreateManyUsersInputEnvelope
  set?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  disconnect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  delete?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  update?: Prisma.attachmentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.attachmentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.attachmentsUpdateManyWithWhereWithoutUsersInput | Prisma.attachmentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
}

export type attachmentsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput> | Prisma.attachmentsCreateWithoutUsersInput[] | Prisma.attachmentsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.attachmentsCreateOrConnectWithoutUsersInput | Prisma.attachmentsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.attachmentsUpsertWithWhereUniqueWithoutUsersInput | Prisma.attachmentsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.attachmentsCreateManyUsersInputEnvelope
  set?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  disconnect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  delete?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  connect?: Prisma.attachmentsWhereUniqueInput | Prisma.attachmentsWhereUniqueInput[]
  update?: Prisma.attachmentsUpdateWithWhereUniqueWithoutUsersInput | Prisma.attachmentsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.attachmentsUpdateManyWithWhereWithoutUsersInput | Prisma.attachmentsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
}

export type attachmentsCreateWithoutRequestsInput = {
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
  users?: Prisma.usersCreateNestedOneWithoutAttachmentsInput
}

export type attachmentsUncheckedCreateWithoutRequestsInput = {
  file_id?: number
  uploader_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsCreateOrConnectWithoutRequestsInput = {
  where: Prisma.attachmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput>
}

export type attachmentsCreateManyRequestsInputEnvelope = {
  data: Prisma.attachmentsCreateManyRequestsInput | Prisma.attachmentsCreateManyRequestsInput[]
  skipDuplicates?: boolean
}

export type attachmentsUpsertWithWhereUniqueWithoutRequestsInput = {
  where: Prisma.attachmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.attachmentsUpdateWithoutRequestsInput, Prisma.attachmentsUncheckedUpdateWithoutRequestsInput>
  create: Prisma.XOR<Prisma.attachmentsCreateWithoutRequestsInput, Prisma.attachmentsUncheckedCreateWithoutRequestsInput>
}

export type attachmentsUpdateWithWhereUniqueWithoutRequestsInput = {
  where: Prisma.attachmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.attachmentsUpdateWithoutRequestsInput, Prisma.attachmentsUncheckedUpdateWithoutRequestsInput>
}

export type attachmentsUpdateManyWithWhereWithoutRequestsInput = {
  where: Prisma.attachmentsScalarWhereInput
  data: Prisma.XOR<Prisma.attachmentsUpdateManyMutationInput, Prisma.attachmentsUncheckedUpdateManyWithoutRequestsInput>
}

export type attachmentsScalarWhereInput = {
  AND?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
  OR?: Prisma.attachmentsScalarWhereInput[]
  NOT?: Prisma.attachmentsScalarWhereInput | Prisma.attachmentsScalarWhereInput[]
  file_id?: Prisma.IntFilter<"attachments"> | number
  request_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  uploader_id?: Prisma.IntNullableFilter<"attachments"> | number | null
  storage_location?: Prisma.StringNullableFilter<"attachments"> | string | null
  file_type?: Prisma.StringNullableFilter<"attachments"> | string | null
  uploaded_at?: Prisma.DateTimeNullableFilter<"attachments"> | Date | string | null
}

export type attachmentsCreateWithoutUsersInput = {
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
  requests?: Prisma.requestsCreateNestedOneWithoutAttachmentsInput
}

export type attachmentsUncheckedCreateWithoutUsersInput = {
  file_id?: number
  request_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsCreateOrConnectWithoutUsersInput = {
  where: Prisma.attachmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput>
}

export type attachmentsCreateManyUsersInputEnvelope = {
  data: Prisma.attachmentsCreateManyUsersInput | Prisma.attachmentsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type attachmentsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.attachmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.attachmentsUpdateWithoutUsersInput, Prisma.attachmentsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.attachmentsCreateWithoutUsersInput, Prisma.attachmentsUncheckedCreateWithoutUsersInput>
}

export type attachmentsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.attachmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.attachmentsUpdateWithoutUsersInput, Prisma.attachmentsUncheckedUpdateWithoutUsersInput>
}

export type attachmentsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.attachmentsScalarWhereInput
  data: Prisma.XOR<Prisma.attachmentsUpdateManyMutationInput, Prisma.attachmentsUncheckedUpdateManyWithoutUsersInput>
}

export type attachmentsCreateManyRequestsInput = {
  file_id?: number
  uploader_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsUpdateWithoutRequestsInput = {
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  users?: Prisma.usersUpdateOneWithoutAttachmentsNestedInput
}

export type attachmentsUncheckedUpdateWithoutRequestsInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  uploader_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsUncheckedUpdateManyWithoutRequestsInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  uploader_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsCreateManyUsersInput = {
  file_id?: number
  request_id?: number | null
  storage_location?: string | null
  file_type?: string | null
  uploaded_at?: Date | string | null
}

export type attachmentsUpdateWithoutUsersInput = {
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  requests?: Prisma.requestsUpdateOneWithoutAttachmentsNestedInput
}

export type attachmentsUncheckedUpdateWithoutUsersInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type attachmentsUncheckedUpdateManyWithoutUsersInput = {
  file_id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  storage_location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  file_type?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  uploaded_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type attachmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  file_id?: boolean
  request_id?: boolean
  uploader_id?: boolean
  storage_location?: boolean
  file_type?: boolean
  uploaded_at?: boolean
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}, ExtArgs["result"]["attachments"]>

export type attachmentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  file_id?: boolean
  request_id?: boolean
  uploader_id?: boolean
  storage_location?: boolean
  file_type?: boolean
  uploaded_at?: boolean
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}, ExtArgs["result"]["attachments"]>

export type attachmentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  file_id?: boolean
  request_id?: boolean
  uploader_id?: boolean
  storage_location?: boolean
  file_type?: boolean
  uploaded_at?: boolean
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}, ExtArgs["result"]["attachments"]>

export type attachmentsSelectScalar = {
  file_id?: boolean
  request_id?: boolean
  uploader_id?: boolean
  storage_location?: boolean
  file_type?: boolean
  uploaded_at?: boolean
}

export type attachmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"file_id" | "request_id" | "uploader_id" | "storage_location" | "file_type" | "uploaded_at", ExtArgs["result"]["attachments"]>
export type attachmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}
export type attachmentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}
export type attachmentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  requests?: boolean | Prisma.attachments$requestsArgs<ExtArgs>
  users?: boolean | Prisma.attachments$usersArgs<ExtArgs>
}

export type $attachmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "attachments"
  objects: {
    requests: Prisma.$requestsPayload<ExtArgs> | null
    users: Prisma.$usersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    file_id: number
    request_id: number | null
    uploader_id: number | null
    storage_location: string | null
    file_type: string | null
    uploaded_at: Date | null
  }, ExtArgs["result"]["attachments"]>
  composites: {}
}

export type attachmentsGetPayload<S extends boolean | null | undefined | attachmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$attachmentsPayload, S>

export type attachmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<attachmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AttachmentsCountAggregateInputType | true
  }

export interface attachmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['attachments'], meta: { name: 'attachments' } }
  /**
   * Find zero or one Attachments that matches the filter.
   * @param {attachmentsFindUniqueArgs} args - Arguments to find a Attachments
   * @example
   * // Get one Attachments
   * const attachments = await prisma.attachments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends attachmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, attachmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Attachments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {attachmentsFindUniqueOrThrowArgs} args - Arguments to find a Attachments
   * @example
   * // Get one Attachments
   * const attachments = await prisma.attachments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends attachmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, attachmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Attachments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsFindFirstArgs} args - Arguments to find a Attachments
   * @example
   * // Get one Attachments
   * const attachments = await prisma.attachments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends attachmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, attachmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Attachments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsFindFirstOrThrowArgs} args - Arguments to find a Attachments
   * @example
   * // Get one Attachments
   * const attachments = await prisma.attachments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends attachmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, attachmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Attachments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Attachments
   * const attachments = await prisma.attachments.findMany()
   * 
   * // Get first 10 Attachments
   * const attachments = await prisma.attachments.findMany({ take: 10 })
   * 
   * // Only select the `file_id`
   * const attachmentsWithFile_idOnly = await prisma.attachments.findMany({ select: { file_id: true } })
   * 
   */
  findMany<T extends attachmentsFindManyArgs>(args?: Prisma.SelectSubset<T, attachmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Attachments.
   * @param {attachmentsCreateArgs} args - Arguments to create a Attachments.
   * @example
   * // Create one Attachments
   * const Attachments = await prisma.attachments.create({
   *   data: {
   *     // ... data to create a Attachments
   *   }
   * })
   * 
   */
  create<T extends attachmentsCreateArgs>(args: Prisma.SelectSubset<T, attachmentsCreateArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Attachments.
   * @param {attachmentsCreateManyArgs} args - Arguments to create many Attachments.
   * @example
   * // Create many Attachments
   * const attachments = await prisma.attachments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends attachmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, attachmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Attachments and returns the data saved in the database.
   * @param {attachmentsCreateManyAndReturnArgs} args - Arguments to create many Attachments.
   * @example
   * // Create many Attachments
   * const attachments = await prisma.attachments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Attachments and only return the `file_id`
   * const attachmentsWithFile_idOnly = await prisma.attachments.createManyAndReturn({
   *   select: { file_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends attachmentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, attachmentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Attachments.
   * @param {attachmentsDeleteArgs} args - Arguments to delete one Attachments.
   * @example
   * // Delete one Attachments
   * const Attachments = await prisma.attachments.delete({
   *   where: {
   *     // ... filter to delete one Attachments
   *   }
   * })
   * 
   */
  delete<T extends attachmentsDeleteArgs>(args: Prisma.SelectSubset<T, attachmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Attachments.
   * @param {attachmentsUpdateArgs} args - Arguments to update one Attachments.
   * @example
   * // Update one Attachments
   * const attachments = await prisma.attachments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends attachmentsUpdateArgs>(args: Prisma.SelectSubset<T, attachmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Attachments.
   * @param {attachmentsDeleteManyArgs} args - Arguments to filter Attachments to delete.
   * @example
   * // Delete a few Attachments
   * const { count } = await prisma.attachments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends attachmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, attachmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Attachments
   * const attachments = await prisma.attachments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends attachmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, attachmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Attachments and returns the data updated in the database.
   * @param {attachmentsUpdateManyAndReturnArgs} args - Arguments to update many Attachments.
   * @example
   * // Update many Attachments
   * const attachments = await prisma.attachments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Attachments and only return the `file_id`
   * const attachmentsWithFile_idOnly = await prisma.attachments.updateManyAndReturn({
   *   select: { file_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends attachmentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, attachmentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Attachments.
   * @param {attachmentsUpsertArgs} args - Arguments to update or create a Attachments.
   * @example
   * // Update or create a Attachments
   * const attachments = await prisma.attachments.upsert({
   *   create: {
   *     // ... data to create a Attachments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Attachments we want to update
   *   }
   * })
   */
  upsert<T extends attachmentsUpsertArgs>(args: Prisma.SelectSubset<T, attachmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__attachmentsClient<runtime.Types.Result.GetResult<Prisma.$attachmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsCountArgs} args - Arguments to filter Attachments to count.
   * @example
   * // Count the number of Attachments
   * const count = await prisma.attachments.count({
   *   where: {
   *     // ... the filter for the Attachments we want to count
   *   }
   * })
  **/
  count<T extends attachmentsCountArgs>(
    args?: Prisma.Subset<T, attachmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AttachmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AttachmentsAggregateArgs>(args: Prisma.Subset<T, AttachmentsAggregateArgs>): Prisma.PrismaPromise<GetAttachmentsAggregateType<T>>

  /**
   * Group by Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {attachmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends attachmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: attachmentsGroupByArgs['orderBy'] }
      : { orderBy?: attachmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, attachmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAttachmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the attachments model
 */
readonly fields: attachmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for attachments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__attachmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  requests<T extends Prisma.attachments$requestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.attachments$requestsArgs<ExtArgs>>): Prisma.Prisma__requestsClient<runtime.Types.Result.GetResult<Prisma.$requestsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.attachments$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.attachments$usersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the attachments model
 */
export interface attachmentsFieldRefs {
  readonly file_id: Prisma.FieldRef<"attachments", 'Int'>
  readonly request_id: Prisma.FieldRef<"attachments", 'Int'>
  readonly uploader_id: Prisma.FieldRef<"attachments", 'Int'>
  readonly storage_location: Prisma.FieldRef<"attachments", 'String'>
  readonly file_type: Prisma.FieldRef<"attachments", 'String'>
  readonly uploaded_at: Prisma.FieldRef<"attachments", 'DateTime'>
}
    

// Custom InputTypes
/**
 * attachments findUnique
 */
export type attachmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter, which attachments to fetch.
   */
  where: Prisma.attachmentsWhereUniqueInput
}

/**
 * attachments findUniqueOrThrow
 */
export type attachmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter, which attachments to fetch.
   */
  where: Prisma.attachmentsWhereUniqueInput
}

/**
 * attachments findFirst
 */
export type attachmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter, which attachments to fetch.
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of attachments to fetch.
   */
  orderBy?: Prisma.attachmentsOrderByWithRelationInput | Prisma.attachmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for attachments.
   */
  cursor?: Prisma.attachmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of attachments.
   */
  distinct?: Prisma.AttachmentsScalarFieldEnum | Prisma.AttachmentsScalarFieldEnum[]
}

/**
 * attachments findFirstOrThrow
 */
export type attachmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter, which attachments to fetch.
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of attachments to fetch.
   */
  orderBy?: Prisma.attachmentsOrderByWithRelationInput | Prisma.attachmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for attachments.
   */
  cursor?: Prisma.attachmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of attachments.
   */
  distinct?: Prisma.AttachmentsScalarFieldEnum | Prisma.AttachmentsScalarFieldEnum[]
}

/**
 * attachments findMany
 */
export type attachmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter, which attachments to fetch.
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of attachments to fetch.
   */
  orderBy?: Prisma.attachmentsOrderByWithRelationInput | Prisma.attachmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing attachments.
   */
  cursor?: Prisma.attachmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` attachments.
   */
  skip?: number
  distinct?: Prisma.AttachmentsScalarFieldEnum | Prisma.AttachmentsScalarFieldEnum[]
}

/**
 * attachments create
 */
export type attachmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a attachments.
   */
  data?: Prisma.XOR<Prisma.attachmentsCreateInput, Prisma.attachmentsUncheckedCreateInput>
}

/**
 * attachments createMany
 */
export type attachmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many attachments.
   */
  data: Prisma.attachmentsCreateManyInput | Prisma.attachmentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * attachments createManyAndReturn
 */
export type attachmentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * The data used to create many attachments.
   */
  data: Prisma.attachmentsCreateManyInput | Prisma.attachmentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * attachments update
 */
export type attachmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a attachments.
   */
  data: Prisma.XOR<Prisma.attachmentsUpdateInput, Prisma.attachmentsUncheckedUpdateInput>
  /**
   * Choose, which attachments to update.
   */
  where: Prisma.attachmentsWhereUniqueInput
}

/**
 * attachments updateMany
 */
export type attachmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update attachments.
   */
  data: Prisma.XOR<Prisma.attachmentsUpdateManyMutationInput, Prisma.attachmentsUncheckedUpdateManyInput>
  /**
   * Filter which attachments to update
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * Limit how many attachments to update.
   */
  limit?: number
}

/**
 * attachments updateManyAndReturn
 */
export type attachmentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * The data used to update attachments.
   */
  data: Prisma.XOR<Prisma.attachmentsUpdateManyMutationInput, Prisma.attachmentsUncheckedUpdateManyInput>
  /**
   * Filter which attachments to update
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * Limit how many attachments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * attachments upsert
 */
export type attachmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the attachments to update in case it exists.
   */
  where: Prisma.attachmentsWhereUniqueInput
  /**
   * In case the attachments found by the `where` argument doesn't exist, create a new attachments with this data.
   */
  create: Prisma.XOR<Prisma.attachmentsCreateInput, Prisma.attachmentsUncheckedCreateInput>
  /**
   * In case the attachments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.attachmentsUpdateInput, Prisma.attachmentsUncheckedUpdateInput>
}

/**
 * attachments delete
 */
export type attachmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
  /**
   * Filter which attachments to delete.
   */
  where: Prisma.attachmentsWhereUniqueInput
}

/**
 * attachments deleteMany
 */
export type attachmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which attachments to delete
   */
  where?: Prisma.attachmentsWhereInput
  /**
   * Limit how many attachments to delete.
   */
  limit?: number
}

/**
 * attachments.requests
 */
export type attachments$requestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the requests
   */
  select?: Prisma.requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the requests
   */
  omit?: Prisma.requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.requestsInclude<ExtArgs> | null
  where?: Prisma.requestsWhereInput
}

/**
 * attachments.users
 */
export type attachments$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * attachments without action
 */
export type attachmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the attachments
   */
  select?: Prisma.attachmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the attachments
   */
  omit?: Prisma.attachmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.attachmentsInclude<ExtArgs> | null
}
