
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `departments` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model departments
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 */
export type departmentsModel = runtime.Types.Result.DefaultSelection<Prisma.$departmentsPayload>

export type AggregateDepartments = {
  _count: DepartmentsCountAggregateOutputType | null
  _avg: DepartmentsAvgAggregateOutputType | null
  _sum: DepartmentsSumAggregateOutputType | null
  _min: DepartmentsMinAggregateOutputType | null
  _max: DepartmentsMaxAggregateOutputType | null
}

export type DepartmentsAvgAggregateOutputType = {
  department_id: number | null
  college_id: number | null
  manager_id: number | null
}

export type DepartmentsSumAggregateOutputType = {
  department_id: number | null
  college_id: number | null
  manager_id: number | null
}

export type DepartmentsMinAggregateOutputType = {
  department_id: number | null
  dept_name: string | null
  college_id: number | null
  manager_id: number | null
}

export type DepartmentsMaxAggregateOutputType = {
  department_id: number | null
  dept_name: string | null
  college_id: number | null
  manager_id: number | null
}

export type DepartmentsCountAggregateOutputType = {
  department_id: number
  dept_name: number
  college_id: number
  manager_id: number
  _all: number
}


export type DepartmentsAvgAggregateInputType = {
  department_id?: true
  college_id?: true
  manager_id?: true
}

export type DepartmentsSumAggregateInputType = {
  department_id?: true
  college_id?: true
  manager_id?: true
}

export type DepartmentsMinAggregateInputType = {
  department_id?: true
  dept_name?: true
  college_id?: true
  manager_id?: true
}

export type DepartmentsMaxAggregateInputType = {
  department_id?: true
  dept_name?: true
  college_id?: true
  manager_id?: true
}

export type DepartmentsCountAggregateInputType = {
  department_id?: true
  dept_name?: true
  college_id?: true
  manager_id?: true
  _all?: true
}

export type DepartmentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which departments to aggregate.
   */
  where?: Prisma.departmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of departments to fetch.
   */
  orderBy?: Prisma.departmentsOrderByWithRelationInput | Prisma.departmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.departmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned departments
  **/
  _count?: true | DepartmentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DepartmentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DepartmentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DepartmentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DepartmentsMaxAggregateInputType
}

export type GetDepartmentsAggregateType<T extends DepartmentsAggregateArgs> = {
      [P in keyof T & keyof AggregateDepartments]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDepartments[P]>
    : Prisma.GetScalarType<T[P], AggregateDepartments[P]>
}




export type departmentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.departmentsWhereInput
  orderBy?: Prisma.departmentsOrderByWithAggregationInput | Prisma.departmentsOrderByWithAggregationInput[]
  by: Prisma.DepartmentsScalarFieldEnum[] | Prisma.DepartmentsScalarFieldEnum
  having?: Prisma.departmentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DepartmentsCountAggregateInputType | true
  _avg?: DepartmentsAvgAggregateInputType
  _sum?: DepartmentsSumAggregateInputType
  _min?: DepartmentsMinAggregateInputType
  _max?: DepartmentsMaxAggregateInputType
}

export type DepartmentsGroupByOutputType = {
  department_id: number
  dept_name: string
  college_id: number
  manager_id: number | null
  _count: DepartmentsCountAggregateOutputType | null
  _avg: DepartmentsAvgAggregateOutputType | null
  _sum: DepartmentsSumAggregateOutputType | null
  _min: DepartmentsMinAggregateOutputType | null
  _max: DepartmentsMaxAggregateOutputType | null
}

type GetDepartmentsGroupByPayload<T extends departmentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DepartmentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DepartmentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DepartmentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DepartmentsGroupByOutputType[P]>
      }
    >
  >



export type departmentsWhereInput = {
  AND?: Prisma.departmentsWhereInput | Prisma.departmentsWhereInput[]
  OR?: Prisma.departmentsWhereInput[]
  NOT?: Prisma.departmentsWhereInput | Prisma.departmentsWhereInput[]
  department_id?: Prisma.IntFilter<"departments"> | number
  dept_name?: Prisma.StringFilter<"departments"> | string
  college_id?: Prisma.IntFilter<"departments"> | number
  manager_id?: Prisma.IntNullableFilter<"departments"> | number | null
  colleges?: Prisma.XOR<Prisma.CollegesScalarRelationFilter, Prisma.collegesWhereInput>
  users_departments_manager_idTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  users_users_department_idTodepartments?: Prisma.UsersListRelationFilter
}

export type departmentsOrderByWithRelationInput = {
  department_id?: Prisma.SortOrder
  dept_name?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrderInput | Prisma.SortOrder
  colleges?: Prisma.collegesOrderByWithRelationInput
  users_departments_manager_idTousers?: Prisma.usersOrderByWithRelationInput
  users_users_department_idTodepartments?: Prisma.usersOrderByRelationAggregateInput
}

export type departmentsWhereUniqueInput = Prisma.AtLeast<{
  department_id?: number
  AND?: Prisma.departmentsWhereInput | Prisma.departmentsWhereInput[]
  OR?: Prisma.departmentsWhereInput[]
  NOT?: Prisma.departmentsWhereInput | Prisma.departmentsWhereInput[]
  dept_name?: Prisma.StringFilter<"departments"> | string
  college_id?: Prisma.IntFilter<"departments"> | number
  manager_id?: Prisma.IntNullableFilter<"departments"> | number | null
  colleges?: Prisma.XOR<Prisma.CollegesScalarRelationFilter, Prisma.collegesWhereInput>
  users_departments_manager_idTousers?: Prisma.XOR<Prisma.UsersNullableScalarRelationFilter, Prisma.usersWhereInput> | null
  users_users_department_idTodepartments?: Prisma.UsersListRelationFilter
}, "department_id">

export type departmentsOrderByWithAggregationInput = {
  department_id?: Prisma.SortOrder
  dept_name?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.departmentsCountOrderByAggregateInput
  _avg?: Prisma.departmentsAvgOrderByAggregateInput
  _max?: Prisma.departmentsMaxOrderByAggregateInput
  _min?: Prisma.departmentsMinOrderByAggregateInput
  _sum?: Prisma.departmentsSumOrderByAggregateInput
}

export type departmentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.departmentsScalarWhereWithAggregatesInput | Prisma.departmentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.departmentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.departmentsScalarWhereWithAggregatesInput | Prisma.departmentsScalarWhereWithAggregatesInput[]
  department_id?: Prisma.IntWithAggregatesFilter<"departments"> | number
  dept_name?: Prisma.StringWithAggregatesFilter<"departments"> | string
  college_id?: Prisma.IntWithAggregatesFilter<"departments"> | number
  manager_id?: Prisma.IntNullableWithAggregatesFilter<"departments"> | number | null
}

export type departmentsCreateInput = {
  dept_name: string
  colleges: Prisma.collegesCreateNestedOneWithoutDepartmentsInput
  users_departments_manager_idTousers?: Prisma.usersCreateNestedOneWithoutDepartments_departments_manager_idTousersInput
  users_users_department_idTodepartments?: Prisma.usersCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsUncheckedCreateInput = {
  department_id?: number
  dept_name: string
  college_id: number
  manager_id?: number | null
  users_users_department_idTodepartments?: Prisma.usersUncheckedCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsUpdateInput = {
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  colleges?: Prisma.collegesUpdateOneRequiredWithoutDepartmentsNestedInput
  users_departments_manager_idTousers?: Prisma.usersUpdateOneWithoutDepartments_departments_manager_idTousersNestedInput
  users_users_department_idTodepartments?: Prisma.usersUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsUncheckedUpdateInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  college_id?: Prisma.IntFieldUpdateOperationsInput | number
  manager_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  users_users_department_idTodepartments?: Prisma.usersUncheckedUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsCreateManyInput = {
  department_id?: number
  dept_name: string
  college_id: number
  manager_id?: number | null
}

export type departmentsUpdateManyMutationInput = {
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type departmentsUncheckedUpdateManyInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  college_id?: Prisma.IntFieldUpdateOperationsInput | number
  manager_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type DepartmentsListRelationFilter = {
  every?: Prisma.departmentsWhereInput
  some?: Prisma.departmentsWhereInput
  none?: Prisma.departmentsWhereInput
}

export type departmentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type departmentsCountOrderByAggregateInput = {
  department_id?: Prisma.SortOrder
  dept_name?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
}

export type departmentsAvgOrderByAggregateInput = {
  department_id?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
}

export type departmentsMaxOrderByAggregateInput = {
  department_id?: Prisma.SortOrder
  dept_name?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
}

export type departmentsMinOrderByAggregateInput = {
  department_id?: Prisma.SortOrder
  dept_name?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
}

export type departmentsSumOrderByAggregateInput = {
  department_id?: Prisma.SortOrder
  college_id?: Prisma.SortOrder
  manager_id?: Prisma.SortOrder
}

export type DepartmentsNullableScalarRelationFilter = {
  is?: Prisma.departmentsWhereInput | null
  isNot?: Prisma.departmentsWhereInput | null
}

export type departmentsCreateNestedManyWithoutCollegesInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput> | Prisma.departmentsCreateWithoutCollegesInput[] | Prisma.departmentsUncheckedCreateWithoutCollegesInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutCollegesInput | Prisma.departmentsCreateOrConnectWithoutCollegesInput[]
  createMany?: Prisma.departmentsCreateManyCollegesInputEnvelope
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
}

export type departmentsUncheckedCreateNestedManyWithoutCollegesInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput> | Prisma.departmentsCreateWithoutCollegesInput[] | Prisma.departmentsUncheckedCreateWithoutCollegesInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutCollegesInput | Prisma.departmentsCreateOrConnectWithoutCollegesInput[]
  createMany?: Prisma.departmentsCreateManyCollegesInputEnvelope
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
}

export type departmentsUpdateManyWithoutCollegesNestedInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput> | Prisma.departmentsCreateWithoutCollegesInput[] | Prisma.departmentsUncheckedCreateWithoutCollegesInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutCollegesInput | Prisma.departmentsCreateOrConnectWithoutCollegesInput[]
  upsert?: Prisma.departmentsUpsertWithWhereUniqueWithoutCollegesInput | Prisma.departmentsUpsertWithWhereUniqueWithoutCollegesInput[]
  createMany?: Prisma.departmentsCreateManyCollegesInputEnvelope
  set?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  disconnect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  delete?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  update?: Prisma.departmentsUpdateWithWhereUniqueWithoutCollegesInput | Prisma.departmentsUpdateWithWhereUniqueWithoutCollegesInput[]
  updateMany?: Prisma.departmentsUpdateManyWithWhereWithoutCollegesInput | Prisma.departmentsUpdateManyWithWhereWithoutCollegesInput[]
  deleteMany?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
}

export type departmentsUncheckedUpdateManyWithoutCollegesNestedInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput> | Prisma.departmentsCreateWithoutCollegesInput[] | Prisma.departmentsUncheckedCreateWithoutCollegesInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutCollegesInput | Prisma.departmentsCreateOrConnectWithoutCollegesInput[]
  upsert?: Prisma.departmentsUpsertWithWhereUniqueWithoutCollegesInput | Prisma.departmentsUpsertWithWhereUniqueWithoutCollegesInput[]
  createMany?: Prisma.departmentsCreateManyCollegesInputEnvelope
  set?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  disconnect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  delete?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  update?: Prisma.departmentsUpdateWithWhereUniqueWithoutCollegesInput | Prisma.departmentsUpdateWithWhereUniqueWithoutCollegesInput[]
  updateMany?: Prisma.departmentsUpdateManyWithWhereWithoutCollegesInput | Prisma.departmentsUpdateManyWithWhereWithoutCollegesInput[]
  deleteMany?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
}

export type departmentsCreateNestedManyWithoutUsers_departments_manager_idTousersInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput> | Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput[] | Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput[]
  createMany?: Prisma.departmentsCreateManyUsers_departments_manager_idTousersInputEnvelope
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
}

export type departmentsCreateNestedOneWithoutUsers_users_department_idTodepartmentsInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedCreateWithoutUsers_users_department_idTodepartmentsInput>
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_users_department_idTodepartmentsInput
  connect?: Prisma.departmentsWhereUniqueInput
}

export type departmentsUncheckedCreateNestedManyWithoutUsers_departments_manager_idTousersInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput> | Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput[] | Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput[]
  createMany?: Prisma.departmentsCreateManyUsers_departments_manager_idTousersInputEnvelope
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
}

export type departmentsUpdateManyWithoutUsers_departments_manager_idTousersNestedInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput> | Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput[] | Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput[]
  upsert?: Prisma.departmentsUpsertWithWhereUniqueWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpsertWithWhereUniqueWithoutUsers_departments_manager_idTousersInput[]
  createMany?: Prisma.departmentsCreateManyUsers_departments_manager_idTousersInputEnvelope
  set?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  disconnect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  delete?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  update?: Prisma.departmentsUpdateWithWhereUniqueWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpdateWithWhereUniqueWithoutUsers_departments_manager_idTousersInput[]
  updateMany?: Prisma.departmentsUpdateManyWithWhereWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpdateManyWithWhereWithoutUsers_departments_manager_idTousersInput[]
  deleteMany?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
}

export type departmentsUpdateOneWithoutUsers_users_department_idTodepartmentsNestedInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedCreateWithoutUsers_users_department_idTodepartmentsInput>
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_users_department_idTodepartmentsInput
  upsert?: Prisma.departmentsUpsertWithoutUsers_users_department_idTodepartmentsInput
  disconnect?: Prisma.departmentsWhereInput | boolean
  delete?: Prisma.departmentsWhereInput | boolean
  connect?: Prisma.departmentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.departmentsUpdateToOneWithWhereWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUpdateWithoutUsers_users_department_idTodepartmentsInput>, Prisma.departmentsUncheckedUpdateWithoutUsers_users_department_idTodepartmentsInput>
}

export type departmentsUncheckedUpdateManyWithoutUsers_departments_manager_idTousersNestedInput = {
  create?: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput> | Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput[] | Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput[]
  connectOrCreate?: Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput[]
  upsert?: Prisma.departmentsUpsertWithWhereUniqueWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpsertWithWhereUniqueWithoutUsers_departments_manager_idTousersInput[]
  createMany?: Prisma.departmentsCreateManyUsers_departments_manager_idTousersInputEnvelope
  set?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  disconnect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  delete?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  connect?: Prisma.departmentsWhereUniqueInput | Prisma.departmentsWhereUniqueInput[]
  update?: Prisma.departmentsUpdateWithWhereUniqueWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpdateWithWhereUniqueWithoutUsers_departments_manager_idTousersInput[]
  updateMany?: Prisma.departmentsUpdateManyWithWhereWithoutUsers_departments_manager_idTousersInput | Prisma.departmentsUpdateManyWithWhereWithoutUsers_departments_manager_idTousersInput[]
  deleteMany?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
}

export type departmentsCreateWithoutCollegesInput = {
  dept_name: string
  users_departments_manager_idTousers?: Prisma.usersCreateNestedOneWithoutDepartments_departments_manager_idTousersInput
  users_users_department_idTodepartments?: Prisma.usersCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsUncheckedCreateWithoutCollegesInput = {
  department_id?: number
  dept_name: string
  manager_id?: number | null
  users_users_department_idTodepartments?: Prisma.usersUncheckedCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsCreateOrConnectWithoutCollegesInput = {
  where: Prisma.departmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput>
}

export type departmentsCreateManyCollegesInputEnvelope = {
  data: Prisma.departmentsCreateManyCollegesInput | Prisma.departmentsCreateManyCollegesInput[]
  skipDuplicates?: boolean
}

export type departmentsUpsertWithWhereUniqueWithoutCollegesInput = {
  where: Prisma.departmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.departmentsUpdateWithoutCollegesInput, Prisma.departmentsUncheckedUpdateWithoutCollegesInput>
  create: Prisma.XOR<Prisma.departmentsCreateWithoutCollegesInput, Prisma.departmentsUncheckedCreateWithoutCollegesInput>
}

export type departmentsUpdateWithWhereUniqueWithoutCollegesInput = {
  where: Prisma.departmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.departmentsUpdateWithoutCollegesInput, Prisma.departmentsUncheckedUpdateWithoutCollegesInput>
}

export type departmentsUpdateManyWithWhereWithoutCollegesInput = {
  where: Prisma.departmentsScalarWhereInput
  data: Prisma.XOR<Prisma.departmentsUpdateManyMutationInput, Prisma.departmentsUncheckedUpdateManyWithoutCollegesInput>
}

export type departmentsScalarWhereInput = {
  AND?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
  OR?: Prisma.departmentsScalarWhereInput[]
  NOT?: Prisma.departmentsScalarWhereInput | Prisma.departmentsScalarWhereInput[]
  department_id?: Prisma.IntFilter<"departments"> | number
  dept_name?: Prisma.StringFilter<"departments"> | string
  college_id?: Prisma.IntFilter<"departments"> | number
  manager_id?: Prisma.IntNullableFilter<"departments"> | number | null
}

export type departmentsCreateWithoutUsers_departments_manager_idTousersInput = {
  dept_name: string
  colleges: Prisma.collegesCreateNestedOneWithoutDepartmentsInput
  users_users_department_idTodepartments?: Prisma.usersCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput = {
  department_id?: number
  dept_name: string
  college_id: number
  users_users_department_idTodepartments?: Prisma.usersUncheckedCreateNestedManyWithoutDepartments_users_department_idTodepartmentsInput
}

export type departmentsCreateOrConnectWithoutUsers_departments_manager_idTousersInput = {
  where: Prisma.departmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput>
}

export type departmentsCreateManyUsers_departments_manager_idTousersInputEnvelope = {
  data: Prisma.departmentsCreateManyUsers_departments_manager_idTousersInput | Prisma.departmentsCreateManyUsers_departments_manager_idTousersInput[]
  skipDuplicates?: boolean
}

export type departmentsCreateWithoutUsers_users_department_idTodepartmentsInput = {
  dept_name: string
  colleges: Prisma.collegesCreateNestedOneWithoutDepartmentsInput
  users_departments_manager_idTousers?: Prisma.usersCreateNestedOneWithoutDepartments_departments_manager_idTousersInput
}

export type departmentsUncheckedCreateWithoutUsers_users_department_idTodepartmentsInput = {
  department_id?: number
  dept_name: string
  college_id: number
  manager_id?: number | null
}

export type departmentsCreateOrConnectWithoutUsers_users_department_idTodepartmentsInput = {
  where: Prisma.departmentsWhereUniqueInput
  create: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedCreateWithoutUsers_users_department_idTodepartmentsInput>
}

export type departmentsUpsertWithWhereUniqueWithoutUsers_departments_manager_idTousersInput = {
  where: Prisma.departmentsWhereUniqueInput
  update: Prisma.XOR<Prisma.departmentsUpdateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedUpdateWithoutUsers_departments_manager_idTousersInput>
  create: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedCreateWithoutUsers_departments_manager_idTousersInput>
}

export type departmentsUpdateWithWhereUniqueWithoutUsers_departments_manager_idTousersInput = {
  where: Prisma.departmentsWhereUniqueInput
  data: Prisma.XOR<Prisma.departmentsUpdateWithoutUsers_departments_manager_idTousersInput, Prisma.departmentsUncheckedUpdateWithoutUsers_departments_manager_idTousersInput>
}

export type departmentsUpdateManyWithWhereWithoutUsers_departments_manager_idTousersInput = {
  where: Prisma.departmentsScalarWhereInput
  data: Prisma.XOR<Prisma.departmentsUpdateManyMutationInput, Prisma.departmentsUncheckedUpdateManyWithoutUsers_departments_manager_idTousersInput>
}

export type departmentsUpsertWithoutUsers_users_department_idTodepartmentsInput = {
  update: Prisma.XOR<Prisma.departmentsUpdateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedUpdateWithoutUsers_users_department_idTodepartmentsInput>
  create: Prisma.XOR<Prisma.departmentsCreateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedCreateWithoutUsers_users_department_idTodepartmentsInput>
  where?: Prisma.departmentsWhereInput
}

export type departmentsUpdateToOneWithWhereWithoutUsers_users_department_idTodepartmentsInput = {
  where?: Prisma.departmentsWhereInput
  data: Prisma.XOR<Prisma.departmentsUpdateWithoutUsers_users_department_idTodepartmentsInput, Prisma.departmentsUncheckedUpdateWithoutUsers_users_department_idTodepartmentsInput>
}

export type departmentsUpdateWithoutUsers_users_department_idTodepartmentsInput = {
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  colleges?: Prisma.collegesUpdateOneRequiredWithoutDepartmentsNestedInput
  users_departments_manager_idTousers?: Prisma.usersUpdateOneWithoutDepartments_departments_manager_idTousersNestedInput
}

export type departmentsUncheckedUpdateWithoutUsers_users_department_idTodepartmentsInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  college_id?: Prisma.IntFieldUpdateOperationsInput | number
  manager_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type departmentsCreateManyCollegesInput = {
  department_id?: number
  dept_name: string
  manager_id?: number | null
}

export type departmentsUpdateWithoutCollegesInput = {
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  users_departments_manager_idTousers?: Prisma.usersUpdateOneWithoutDepartments_departments_manager_idTousersNestedInput
  users_users_department_idTodepartments?: Prisma.usersUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsUncheckedUpdateWithoutCollegesInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  manager_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  users_users_department_idTodepartments?: Prisma.usersUncheckedUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsUncheckedUpdateManyWithoutCollegesInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  manager_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type departmentsCreateManyUsers_departments_manager_idTousersInput = {
  department_id?: number
  dept_name: string
  college_id: number
}

export type departmentsUpdateWithoutUsers_departments_manager_idTousersInput = {
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  colleges?: Prisma.collegesUpdateOneRequiredWithoutDepartmentsNestedInput
  users_users_department_idTodepartments?: Prisma.usersUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsUncheckedUpdateWithoutUsers_departments_manager_idTousersInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  college_id?: Prisma.IntFieldUpdateOperationsInput | number
  users_users_department_idTodepartments?: Prisma.usersUncheckedUpdateManyWithoutDepartments_users_department_idTodepartmentsNestedInput
}

export type departmentsUncheckedUpdateManyWithoutUsers_departments_manager_idTousersInput = {
  department_id?: Prisma.IntFieldUpdateOperationsInput | number
  dept_name?: Prisma.StringFieldUpdateOperationsInput | string
  college_id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type DepartmentsCountOutputType
 */

export type DepartmentsCountOutputType = {
  users_users_department_idTodepartments: number
}

export type DepartmentsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users_users_department_idTodepartments?: boolean | DepartmentsCountOutputTypeCountUsers_users_department_idTodepartmentsArgs
}

/**
 * DepartmentsCountOutputType without action
 */
export type DepartmentsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DepartmentsCountOutputType
   */
  select?: Prisma.DepartmentsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DepartmentsCountOutputType without action
 */
export type DepartmentsCountOutputTypeCountUsers_users_department_idTodepartmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.usersWhereInput
}


export type departmentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  department_id?: boolean
  dept_name?: boolean
  college_id?: boolean
  manager_id?: boolean
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
  users_users_department_idTodepartments?: boolean | Prisma.departments$users_users_department_idTodepartmentsArgs<ExtArgs>
  _count?: boolean | Prisma.DepartmentsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["departments"]>

export type departmentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  department_id?: boolean
  dept_name?: boolean
  college_id?: boolean
  manager_id?: boolean
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
}, ExtArgs["result"]["departments"]>

export type departmentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  department_id?: boolean
  dept_name?: boolean
  college_id?: boolean
  manager_id?: boolean
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
}, ExtArgs["result"]["departments"]>

export type departmentsSelectScalar = {
  department_id?: boolean
  dept_name?: boolean
  college_id?: boolean
  manager_id?: boolean
}

export type departmentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"department_id" | "dept_name" | "college_id" | "manager_id", ExtArgs["result"]["departments"]>
export type departmentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
  users_users_department_idTodepartments?: boolean | Prisma.departments$users_users_department_idTodepartmentsArgs<ExtArgs>
  _count?: boolean | Prisma.DepartmentsCountOutputTypeDefaultArgs<ExtArgs>
}
export type departmentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
}
export type departmentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  colleges?: boolean | Prisma.collegesDefaultArgs<ExtArgs>
  users_departments_manager_idTousers?: boolean | Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>
}

export type $departmentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "departments"
  objects: {
    colleges: Prisma.$collegesPayload<ExtArgs>
    users_departments_manager_idTousers: Prisma.$usersPayload<ExtArgs> | null
    users_users_department_idTodepartments: Prisma.$usersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    department_id: number
    dept_name: string
    college_id: number
    manager_id: number | null
  }, ExtArgs["result"]["departments"]>
  composites: {}
}

export type departmentsGetPayload<S extends boolean | null | undefined | departmentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$departmentsPayload, S>

export type departmentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<departmentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DepartmentsCountAggregateInputType | true
  }

export interface departmentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['departments'], meta: { name: 'departments' } }
  /**
   * Find zero or one Departments that matches the filter.
   * @param {departmentsFindUniqueArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends departmentsFindUniqueArgs>(args: Prisma.SelectSubset<T, departmentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Departments that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {departmentsFindUniqueOrThrowArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends departmentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, departmentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Departments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsFindFirstArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends departmentsFindFirstArgs>(args?: Prisma.SelectSubset<T, departmentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Departments that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsFindFirstOrThrowArgs} args - Arguments to find a Departments
   * @example
   * // Get one Departments
   * const departments = await prisma.departments.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends departmentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, departmentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Departments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Departments
   * const departments = await prisma.departments.findMany()
   * 
   * // Get first 10 Departments
   * const departments = await prisma.departments.findMany({ take: 10 })
   * 
   * // Only select the `department_id`
   * const departmentsWithDepartment_idOnly = await prisma.departments.findMany({ select: { department_id: true } })
   * 
   */
  findMany<T extends departmentsFindManyArgs>(args?: Prisma.SelectSubset<T, departmentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Departments.
   * @param {departmentsCreateArgs} args - Arguments to create a Departments.
   * @example
   * // Create one Departments
   * const Departments = await prisma.departments.create({
   *   data: {
   *     // ... data to create a Departments
   *   }
   * })
   * 
   */
  create<T extends departmentsCreateArgs>(args: Prisma.SelectSubset<T, departmentsCreateArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Departments.
   * @param {departmentsCreateManyArgs} args - Arguments to create many Departments.
   * @example
   * // Create many Departments
   * const departments = await prisma.departments.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends departmentsCreateManyArgs>(args?: Prisma.SelectSubset<T, departmentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Departments and returns the data saved in the database.
   * @param {departmentsCreateManyAndReturnArgs} args - Arguments to create many Departments.
   * @example
   * // Create many Departments
   * const departments = await prisma.departments.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Departments and only return the `department_id`
   * const departmentsWithDepartment_idOnly = await prisma.departments.createManyAndReturn({
   *   select: { department_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends departmentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, departmentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Departments.
   * @param {departmentsDeleteArgs} args - Arguments to delete one Departments.
   * @example
   * // Delete one Departments
   * const Departments = await prisma.departments.delete({
   *   where: {
   *     // ... filter to delete one Departments
   *   }
   * })
   * 
   */
  delete<T extends departmentsDeleteArgs>(args: Prisma.SelectSubset<T, departmentsDeleteArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Departments.
   * @param {departmentsUpdateArgs} args - Arguments to update one Departments.
   * @example
   * // Update one Departments
   * const departments = await prisma.departments.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends departmentsUpdateArgs>(args: Prisma.SelectSubset<T, departmentsUpdateArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Departments.
   * @param {departmentsDeleteManyArgs} args - Arguments to filter Departments to delete.
   * @example
   * // Delete a few Departments
   * const { count } = await prisma.departments.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends departmentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, departmentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Departments
   * const departments = await prisma.departments.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends departmentsUpdateManyArgs>(args: Prisma.SelectSubset<T, departmentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Departments and returns the data updated in the database.
   * @param {departmentsUpdateManyAndReturnArgs} args - Arguments to update many Departments.
   * @example
   * // Update many Departments
   * const departments = await prisma.departments.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Departments and only return the `department_id`
   * const departmentsWithDepartment_idOnly = await prisma.departments.updateManyAndReturn({
   *   select: { department_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends departmentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, departmentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Departments.
   * @param {departmentsUpsertArgs} args - Arguments to update or create a Departments.
   * @example
   * // Update or create a Departments
   * const departments = await prisma.departments.upsert({
   *   create: {
   *     // ... data to create a Departments
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Departments we want to update
   *   }
   * })
   */
  upsert<T extends departmentsUpsertArgs>(args: Prisma.SelectSubset<T, departmentsUpsertArgs<ExtArgs>>): Prisma.Prisma__departmentsClient<runtime.Types.Result.GetResult<Prisma.$departmentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsCountArgs} args - Arguments to filter Departments to count.
   * @example
   * // Count the number of Departments
   * const count = await prisma.departments.count({
   *   where: {
   *     // ... the filter for the Departments we want to count
   *   }
   * })
  **/
  count<T extends departmentsCountArgs>(
    args?: Prisma.Subset<T, departmentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DepartmentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DepartmentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DepartmentsAggregateArgs>(args: Prisma.Subset<T, DepartmentsAggregateArgs>): Prisma.PrismaPromise<GetDepartmentsAggregateType<T>>

  /**
   * Group by Departments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {departmentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends departmentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: departmentsGroupByArgs['orderBy'] }
      : { orderBy?: departmentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, departmentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDepartmentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the departments model
 */
readonly fields: departmentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for departments.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__departmentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  colleges<T extends Prisma.collegesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.collegesDefaultArgs<ExtArgs>>): Prisma.Prisma__collegesClient<runtime.Types.Result.GetResult<Prisma.$collegesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users_departments_manager_idTousers<T extends Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.departments$users_departments_manager_idTousersArgs<ExtArgs>>): Prisma.Prisma__usersClient<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  users_users_department_idTodepartments<T extends Prisma.departments$users_users_department_idTodepartmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.departments$users_users_department_idTodepartmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$usersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the departments model
 */
export interface departmentsFieldRefs {
  readonly department_id: Prisma.FieldRef<"departments", 'Int'>
  readonly dept_name: Prisma.FieldRef<"departments", 'String'>
  readonly college_id: Prisma.FieldRef<"departments", 'Int'>
  readonly manager_id: Prisma.FieldRef<"departments", 'Int'>
}
    

// Custom InputTypes
/**
 * departments findUnique
 */
export type departmentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter, which departments to fetch.
   */
  where: Prisma.departmentsWhereUniqueInput
}

/**
 * departments findUniqueOrThrow
 */
export type departmentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter, which departments to fetch.
   */
  where: Prisma.departmentsWhereUniqueInput
}

/**
 * departments findFirst
 */
export type departmentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter, which departments to fetch.
   */
  where?: Prisma.departmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of departments to fetch.
   */
  orderBy?: Prisma.departmentsOrderByWithRelationInput | Prisma.departmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for departments.
   */
  cursor?: Prisma.departmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of departments.
   */
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * departments findFirstOrThrow
 */
export type departmentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter, which departments to fetch.
   */
  where?: Prisma.departmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of departments to fetch.
   */
  orderBy?: Prisma.departmentsOrderByWithRelationInput | Prisma.departmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for departments.
   */
  cursor?: Prisma.departmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` departments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of departments.
   */
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * departments findMany
 */
export type departmentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter, which departments to fetch.
   */
  where?: Prisma.departmentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of departments to fetch.
   */
  orderBy?: Prisma.departmentsOrderByWithRelationInput | Prisma.departmentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing departments.
   */
  cursor?: Prisma.departmentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` departments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` departments.
   */
  skip?: number
  distinct?: Prisma.DepartmentsScalarFieldEnum | Prisma.DepartmentsScalarFieldEnum[]
}

/**
 * departments create
 */
export type departmentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * The data needed to create a departments.
   */
  data: Prisma.XOR<Prisma.departmentsCreateInput, Prisma.departmentsUncheckedCreateInput>
}

/**
 * departments createMany
 */
export type departmentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many departments.
   */
  data: Prisma.departmentsCreateManyInput | Prisma.departmentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * departments createManyAndReturn
 */
export type departmentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * The data used to create many departments.
   */
  data: Prisma.departmentsCreateManyInput | Prisma.departmentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * departments update
 */
export type departmentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * The data needed to update a departments.
   */
  data: Prisma.XOR<Prisma.departmentsUpdateInput, Prisma.departmentsUncheckedUpdateInput>
  /**
   * Choose, which departments to update.
   */
  where: Prisma.departmentsWhereUniqueInput
}

/**
 * departments updateMany
 */
export type departmentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update departments.
   */
  data: Prisma.XOR<Prisma.departmentsUpdateManyMutationInput, Prisma.departmentsUncheckedUpdateManyInput>
  /**
   * Filter which departments to update
   */
  where?: Prisma.departmentsWhereInput
  /**
   * Limit how many departments to update.
   */
  limit?: number
}

/**
 * departments updateManyAndReturn
 */
export type departmentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * The data used to update departments.
   */
  data: Prisma.XOR<Prisma.departmentsUpdateManyMutationInput, Prisma.departmentsUncheckedUpdateManyInput>
  /**
   * Filter which departments to update
   */
  where?: Prisma.departmentsWhereInput
  /**
   * Limit how many departments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * departments upsert
 */
export type departmentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * The filter to search for the departments to update in case it exists.
   */
  where: Prisma.departmentsWhereUniqueInput
  /**
   * In case the departments found by the `where` argument doesn't exist, create a new departments with this data.
   */
  create: Prisma.XOR<Prisma.departmentsCreateInput, Prisma.departmentsUncheckedCreateInput>
  /**
   * In case the departments was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.departmentsUpdateInput, Prisma.departmentsUncheckedUpdateInput>
}

/**
 * departments delete
 */
export type departmentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
  /**
   * Filter which departments to delete.
   */
  where: Prisma.departmentsWhereUniqueInput
}

/**
 * departments deleteMany
 */
export type departmentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which departments to delete
   */
  where?: Prisma.departmentsWhereInput
  /**
   * Limit how many departments to delete.
   */
  limit?: number
}

/**
 * departments.users_departments_manager_idTousers
 */
export type departments$users_departments_manager_idTousersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
}

/**
 * departments.users_users_department_idTodepartments
 */
export type departments$users_users_department_idTodepartmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the users
   */
  select?: Prisma.usersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the users
   */
  omit?: Prisma.usersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.usersInclude<ExtArgs> | null
  where?: Prisma.usersWhereInput
  orderBy?: Prisma.usersOrderByWithRelationInput | Prisma.usersOrderByWithRelationInput[]
  cursor?: Prisma.usersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UsersScalarFieldEnum | Prisma.UsersScalarFieldEnum[]
}

/**
 * departments without action
 */
export type departmentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the departments
   */
  select?: Prisma.departmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the departments
   */
  omit?: Prisma.departmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.departmentsInclude<ExtArgs> | null
}
