
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `workflow_steps` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model workflow_steps
 * 
 */
export type workflow_stepsModel = runtime.Types.Result.DefaultSelection<Prisma.$workflow_stepsPayload>

export type AggregateWorkflow_steps = {
  _count: Workflow_stepsCountAggregateOutputType | null
  _avg: Workflow_stepsAvgAggregateOutputType | null
  _sum: Workflow_stepsSumAggregateOutputType | null
  _min: Workflow_stepsMinAggregateOutputType | null
  _max: Workflow_stepsMaxAggregateOutputType | null
}

export type Workflow_stepsAvgAggregateOutputType = {
  step_id: number | null
  workflow_id: number | null
  order: number | null
  approver_role_id: number | null
  sla_hours: number | null
}

export type Workflow_stepsSumAggregateOutputType = {
  step_id: number | null
  workflow_id: number | null
  order: number | null
  approver_role_id: number | null
  sla_hours: number | null
}

export type Workflow_stepsMinAggregateOutputType = {
  step_id: number | null
  workflow_id: number | null
  order: number | null
  name: string | null
  approver_role_id: number | null
  sla_hours: number | null
  is_final: boolean | null
}

export type Workflow_stepsMaxAggregateOutputType = {
  step_id: number | null
  workflow_id: number | null
  order: number | null
  name: string | null
  approver_role_id: number | null
  sla_hours: number | null
  is_final: boolean | null
}

export type Workflow_stepsCountAggregateOutputType = {
  step_id: number
  workflow_id: number
  order: number
  name: number
  approver_role_id: number
  sla_hours: number
  is_final: number
  _all: number
}


export type Workflow_stepsAvgAggregateInputType = {
  step_id?: true
  workflow_id?: true
  order?: true
  approver_role_id?: true
  sla_hours?: true
}

export type Workflow_stepsSumAggregateInputType = {
  step_id?: true
  workflow_id?: true
  order?: true
  approver_role_id?: true
  sla_hours?: true
}

export type Workflow_stepsMinAggregateInputType = {
  step_id?: true
  workflow_id?: true
  order?: true
  name?: true
  approver_role_id?: true
  sla_hours?: true
  is_final?: true
}

export type Workflow_stepsMaxAggregateInputType = {
  step_id?: true
  workflow_id?: true
  order?: true
  name?: true
  approver_role_id?: true
  sla_hours?: true
  is_final?: true
}

export type Workflow_stepsCountAggregateInputType = {
  step_id?: true
  workflow_id?: true
  order?: true
  name?: true
  approver_role_id?: true
  sla_hours?: true
  is_final?: true
  _all?: true
}

export type Workflow_stepsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which workflow_steps to aggregate.
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of workflow_steps to fetch.
   */
  orderBy?: Prisma.workflow_stepsOrderByWithRelationInput | Prisma.workflow_stepsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.workflow_stepsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` workflow_steps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` workflow_steps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned workflow_steps
  **/
  _count?: true | Workflow_stepsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Workflow_stepsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Workflow_stepsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Workflow_stepsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Workflow_stepsMaxAggregateInputType
}

export type GetWorkflow_stepsAggregateType<T extends Workflow_stepsAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflow_steps]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflow_steps[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflow_steps[P]>
}




export type workflow_stepsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.workflow_stepsWhereInput
  orderBy?: Prisma.workflow_stepsOrderByWithAggregationInput | Prisma.workflow_stepsOrderByWithAggregationInput[]
  by: Prisma.Workflow_stepsScalarFieldEnum[] | Prisma.Workflow_stepsScalarFieldEnum
  having?: Prisma.workflow_stepsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Workflow_stepsCountAggregateInputType | true
  _avg?: Workflow_stepsAvgAggregateInputType
  _sum?: Workflow_stepsSumAggregateInputType
  _min?: Workflow_stepsMinAggregateInputType
  _max?: Workflow_stepsMaxAggregateInputType
}

export type Workflow_stepsGroupByOutputType = {
  step_id: number
  workflow_id: number | null
  order: number
  name: string | null
  approver_role_id: number | null
  sla_hours: number | null
  is_final: boolean | null
  _count: Workflow_stepsCountAggregateOutputType | null
  _avg: Workflow_stepsAvgAggregateOutputType | null
  _sum: Workflow_stepsSumAggregateOutputType | null
  _min: Workflow_stepsMinAggregateOutputType | null
  _max: Workflow_stepsMaxAggregateOutputType | null
}

type GetWorkflow_stepsGroupByPayload<T extends workflow_stepsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Workflow_stepsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Workflow_stepsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Workflow_stepsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Workflow_stepsGroupByOutputType[P]>
      }
    >
  >



export type workflow_stepsWhereInput = {
  AND?: Prisma.workflow_stepsWhereInput | Prisma.workflow_stepsWhereInput[]
  OR?: Prisma.workflow_stepsWhereInput[]
  NOT?: Prisma.workflow_stepsWhereInput | Prisma.workflow_stepsWhereInput[]
  step_id?: Prisma.IntFilter<"workflow_steps"> | number
  workflow_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  order?: Prisma.IntFilter<"workflow_steps"> | number
  name?: Prisma.StringNullableFilter<"workflow_steps"> | string | null
  approver_role_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  sla_hours?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  is_final?: Prisma.BoolNullableFilter<"workflow_steps"> | boolean | null
  request_actions?: Prisma.Request_actionsListRelationFilter
  requests?: Prisma.RequestsListRelationFilter
  roles?: Prisma.XOR<Prisma.RolesNullableScalarRelationFilter, Prisma.rolesWhereInput> | null
  workflows?: Prisma.XOR<Prisma.WorkflowsNullableScalarRelationFilter, Prisma.workflowsWhereInput> | null
}

export type workflow_stepsOrderByWithRelationInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  approver_role_id?: Prisma.SortOrderInput | Prisma.SortOrder
  sla_hours?: Prisma.SortOrderInput | Prisma.SortOrder
  is_final?: Prisma.SortOrderInput | Prisma.SortOrder
  request_actions?: Prisma.request_actionsOrderByRelationAggregateInput
  requests?: Prisma.requestsOrderByRelationAggregateInput
  roles?: Prisma.rolesOrderByWithRelationInput
  workflows?: Prisma.workflowsOrderByWithRelationInput
}

export type workflow_stepsWhereUniqueInput = Prisma.AtLeast<{
  step_id?: number
  AND?: Prisma.workflow_stepsWhereInput | Prisma.workflow_stepsWhereInput[]
  OR?: Prisma.workflow_stepsWhereInput[]
  NOT?: Prisma.workflow_stepsWhereInput | Prisma.workflow_stepsWhereInput[]
  workflow_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  order?: Prisma.IntFilter<"workflow_steps"> | number
  name?: Prisma.StringNullableFilter<"workflow_steps"> | string | null
  approver_role_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  sla_hours?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  is_final?: Prisma.BoolNullableFilter<"workflow_steps"> | boolean | null
  request_actions?: Prisma.Request_actionsListRelationFilter
  requests?: Prisma.RequestsListRelationFilter
  roles?: Prisma.XOR<Prisma.RolesNullableScalarRelationFilter, Prisma.rolesWhereInput> | null
  workflows?: Prisma.XOR<Prisma.WorkflowsNullableScalarRelationFilter, Prisma.workflowsWhereInput> | null
}, "step_id">

export type workflow_stepsOrderByWithAggregationInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  approver_role_id?: Prisma.SortOrderInput | Prisma.SortOrder
  sla_hours?: Prisma.SortOrderInput | Prisma.SortOrder
  is_final?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.workflow_stepsCountOrderByAggregateInput
  _avg?: Prisma.workflow_stepsAvgOrderByAggregateInput
  _max?: Prisma.workflow_stepsMaxOrderByAggregateInput
  _min?: Prisma.workflow_stepsMinOrderByAggregateInput
  _sum?: Prisma.workflow_stepsSumOrderByAggregateInput
}

export type workflow_stepsScalarWhereWithAggregatesInput = {
  AND?: Prisma.workflow_stepsScalarWhereWithAggregatesInput | Prisma.workflow_stepsScalarWhereWithAggregatesInput[]
  OR?: Prisma.workflow_stepsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.workflow_stepsScalarWhereWithAggregatesInput | Prisma.workflow_stepsScalarWhereWithAggregatesInput[]
  step_id?: Prisma.IntWithAggregatesFilter<"workflow_steps"> | number
  workflow_id?: Prisma.IntNullableWithAggregatesFilter<"workflow_steps"> | number | null
  order?: Prisma.IntWithAggregatesFilter<"workflow_steps"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"workflow_steps"> | string | null
  approver_role_id?: Prisma.IntNullableWithAggregatesFilter<"workflow_steps"> | number | null
  sla_hours?: Prisma.IntNullableWithAggregatesFilter<"workflow_steps"> | number | null
  is_final?: Prisma.BoolNullableWithAggregatesFilter<"workflow_steps"> | boolean | null
}

export type workflow_stepsCreateInput = {
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsCreateNestedManyWithoutWorkflow_stepsInput
  roles?: Prisma.rolesCreateNestedOneWithoutWorkflow_stepsInput
  workflows?: Prisma.workflowsCreateNestedOneWithoutWorkflow_stepsInput
}

export type workflow_stepsUncheckedCreateInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
}

export type workflow_stepsUpdateInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUpdateManyWithoutWorkflow_stepsNestedInput
  roles?: Prisma.rolesUpdateOneWithoutWorkflow_stepsNestedInput
  workflows?: Prisma.workflowsUpdateOneWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsCreateManyInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
}

export type workflow_stepsUpdateManyMutationInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type workflow_stepsUncheckedUpdateManyInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type Workflow_stepsNullableScalarRelationFilter = {
  is?: Prisma.workflow_stepsWhereInput | null
  isNot?: Prisma.workflow_stepsWhereInput | null
}

export type Workflow_stepsListRelationFilter = {
  every?: Prisma.workflow_stepsWhereInput
  some?: Prisma.workflow_stepsWhereInput
  none?: Prisma.workflow_stepsWhereInput
}

export type workflow_stepsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type workflow_stepsCountOrderByAggregateInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  approver_role_id?: Prisma.SortOrder
  sla_hours?: Prisma.SortOrder
  is_final?: Prisma.SortOrder
}

export type workflow_stepsAvgOrderByAggregateInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  approver_role_id?: Prisma.SortOrder
  sla_hours?: Prisma.SortOrder
}

export type workflow_stepsMaxOrderByAggregateInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  approver_role_id?: Prisma.SortOrder
  sla_hours?: Prisma.SortOrder
  is_final?: Prisma.SortOrder
}

export type workflow_stepsMinOrderByAggregateInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  approver_role_id?: Prisma.SortOrder
  sla_hours?: Prisma.SortOrder
  is_final?: Prisma.SortOrder
}

export type workflow_stepsSumOrderByAggregateInput = {
  step_id?: Prisma.SortOrder
  workflow_id?: Prisma.SortOrder
  order?: Prisma.SortOrder
  approver_role_id?: Prisma.SortOrder
  sla_hours?: Prisma.SortOrder
}

export type workflow_stepsCreateNestedOneWithoutRequest_actionsInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequest_actionsInput>
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRequest_actionsInput
  connect?: Prisma.workflow_stepsWhereUniqueInput
}

export type workflow_stepsUpdateOneWithoutRequest_actionsNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequest_actionsInput>
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRequest_actionsInput
  upsert?: Prisma.workflow_stepsUpsertWithoutRequest_actionsInput
  disconnect?: Prisma.workflow_stepsWhereInput | boolean
  delete?: Prisma.workflow_stepsWhereInput | boolean
  connect?: Prisma.workflow_stepsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.workflow_stepsUpdateToOneWithWhereWithoutRequest_actionsInput, Prisma.workflow_stepsUpdateWithoutRequest_actionsInput>, Prisma.workflow_stepsUncheckedUpdateWithoutRequest_actionsInput>
}

export type workflow_stepsCreateNestedOneWithoutRequestsInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequestsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRequestsInput
  connect?: Prisma.workflow_stepsWhereUniqueInput
}

export type workflow_stepsUpdateOneWithoutRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequestsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequestsInput>
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRequestsInput
  upsert?: Prisma.workflow_stepsUpsertWithoutRequestsInput
  disconnect?: Prisma.workflow_stepsWhereInput | boolean
  delete?: Prisma.workflow_stepsWhereInput | boolean
  connect?: Prisma.workflow_stepsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.workflow_stepsUpdateToOneWithWhereWithoutRequestsInput, Prisma.workflow_stepsUpdateWithoutRequestsInput>, Prisma.workflow_stepsUncheckedUpdateWithoutRequestsInput>
}

export type workflow_stepsCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput> | Prisma.workflow_stepsCreateWithoutRolesInput[] | Prisma.workflow_stepsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRolesInput | Prisma.workflow_stepsCreateOrConnectWithoutRolesInput[]
  createMany?: Prisma.workflow_stepsCreateManyRolesInputEnvelope
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
}

export type workflow_stepsUncheckedCreateNestedManyWithoutRolesInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput> | Prisma.workflow_stepsCreateWithoutRolesInput[] | Prisma.workflow_stepsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRolesInput | Prisma.workflow_stepsCreateOrConnectWithoutRolesInput[]
  createMany?: Prisma.workflow_stepsCreateManyRolesInputEnvelope
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
}

export type workflow_stepsUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput> | Prisma.workflow_stepsCreateWithoutRolesInput[] | Prisma.workflow_stepsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRolesInput | Prisma.workflow_stepsCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.workflow_stepsUpsertWithWhereUniqueWithoutRolesInput | Prisma.workflow_stepsUpsertWithWhereUniqueWithoutRolesInput[]
  createMany?: Prisma.workflow_stepsCreateManyRolesInputEnvelope
  set?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  disconnect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  delete?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  update?: Prisma.workflow_stepsUpdateWithWhereUniqueWithoutRolesInput | Prisma.workflow_stepsUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.workflow_stepsUpdateManyWithWhereWithoutRolesInput | Prisma.workflow_stepsUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
}

export type workflow_stepsUncheckedUpdateManyWithoutRolesNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput> | Prisma.workflow_stepsCreateWithoutRolesInput[] | Prisma.workflow_stepsUncheckedCreateWithoutRolesInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutRolesInput | Prisma.workflow_stepsCreateOrConnectWithoutRolesInput[]
  upsert?: Prisma.workflow_stepsUpsertWithWhereUniqueWithoutRolesInput | Prisma.workflow_stepsUpsertWithWhereUniqueWithoutRolesInput[]
  createMany?: Prisma.workflow_stepsCreateManyRolesInputEnvelope
  set?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  disconnect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  delete?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  update?: Prisma.workflow_stepsUpdateWithWhereUniqueWithoutRolesInput | Prisma.workflow_stepsUpdateWithWhereUniqueWithoutRolesInput[]
  updateMany?: Prisma.workflow_stepsUpdateManyWithWhereWithoutRolesInput | Prisma.workflow_stepsUpdateManyWithWhereWithoutRolesInput[]
  deleteMany?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
}

export type workflow_stepsCreateNestedManyWithoutWorkflowsInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput> | Prisma.workflow_stepsCreateWithoutWorkflowsInput[] | Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput | Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput[]
  createMany?: Prisma.workflow_stepsCreateManyWorkflowsInputEnvelope
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
}

export type workflow_stepsUncheckedCreateNestedManyWithoutWorkflowsInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput> | Prisma.workflow_stepsCreateWithoutWorkflowsInput[] | Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput | Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput[]
  createMany?: Prisma.workflow_stepsCreateManyWorkflowsInputEnvelope
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
}

export type workflow_stepsUpdateManyWithoutWorkflowsNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput> | Prisma.workflow_stepsCreateWithoutWorkflowsInput[] | Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput | Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput[]
  upsert?: Prisma.workflow_stepsUpsertWithWhereUniqueWithoutWorkflowsInput | Prisma.workflow_stepsUpsertWithWhereUniqueWithoutWorkflowsInput[]
  createMany?: Prisma.workflow_stepsCreateManyWorkflowsInputEnvelope
  set?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  disconnect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  delete?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  update?: Prisma.workflow_stepsUpdateWithWhereUniqueWithoutWorkflowsInput | Prisma.workflow_stepsUpdateWithWhereUniqueWithoutWorkflowsInput[]
  updateMany?: Prisma.workflow_stepsUpdateManyWithWhereWithoutWorkflowsInput | Prisma.workflow_stepsUpdateManyWithWhereWithoutWorkflowsInput[]
  deleteMany?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
}

export type workflow_stepsUncheckedUpdateManyWithoutWorkflowsNestedInput = {
  create?: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput> | Prisma.workflow_stepsCreateWithoutWorkflowsInput[] | Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput[]
  connectOrCreate?: Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput | Prisma.workflow_stepsCreateOrConnectWithoutWorkflowsInput[]
  upsert?: Prisma.workflow_stepsUpsertWithWhereUniqueWithoutWorkflowsInput | Prisma.workflow_stepsUpsertWithWhereUniqueWithoutWorkflowsInput[]
  createMany?: Prisma.workflow_stepsCreateManyWorkflowsInputEnvelope
  set?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  disconnect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  delete?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  connect?: Prisma.workflow_stepsWhereUniqueInput | Prisma.workflow_stepsWhereUniqueInput[]
  update?: Prisma.workflow_stepsUpdateWithWhereUniqueWithoutWorkflowsInput | Prisma.workflow_stepsUpdateWithWhereUniqueWithoutWorkflowsInput[]
  updateMany?: Prisma.workflow_stepsUpdateManyWithWhereWithoutWorkflowsInput | Prisma.workflow_stepsUpdateManyWithWhereWithoutWorkflowsInput[]
  deleteMany?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
}

export type workflow_stepsCreateWithoutRequest_actionsInput = {
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  requests?: Prisma.requestsCreateNestedManyWithoutWorkflow_stepsInput
  roles?: Prisma.rolesCreateNestedOneWithoutWorkflow_stepsInput
  workflows?: Prisma.workflowsCreateNestedOneWithoutWorkflow_stepsInput
}

export type workflow_stepsUncheckedCreateWithoutRequest_actionsInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
  requests?: Prisma.requestsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
}

export type workflow_stepsCreateOrConnectWithoutRequest_actionsInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequest_actionsInput>
}

export type workflow_stepsUpsertWithoutRequest_actionsInput = {
  update: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedUpdateWithoutRequest_actionsInput>
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequest_actionsInput>
  where?: Prisma.workflow_stepsWhereInput
}

export type workflow_stepsUpdateToOneWithWhereWithoutRequest_actionsInput = {
  where?: Prisma.workflow_stepsWhereInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRequest_actionsInput, Prisma.workflow_stepsUncheckedUpdateWithoutRequest_actionsInput>
}

export type workflow_stepsUpdateWithoutRequest_actionsInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  requests?: Prisma.requestsUpdateManyWithoutWorkflow_stepsNestedInput
  roles?: Prisma.rolesUpdateOneWithoutWorkflow_stepsNestedInput
  workflows?: Prisma.workflowsUpdateOneWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateWithoutRequest_actionsInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  requests?: Prisma.requestsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsCreateWithoutRequestsInput = {
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsCreateNestedManyWithoutWorkflow_stepsInput
  roles?: Prisma.rolesCreateNestedOneWithoutWorkflow_stepsInput
  workflows?: Prisma.workflowsCreateNestedOneWithoutWorkflow_stepsInput
}

export type workflow_stepsUncheckedCreateWithoutRequestsInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
}

export type workflow_stepsCreateOrConnectWithoutRequestsInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequestsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequestsInput>
}

export type workflow_stepsUpsertWithoutRequestsInput = {
  update: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRequestsInput, Prisma.workflow_stepsUncheckedUpdateWithoutRequestsInput>
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRequestsInput, Prisma.workflow_stepsUncheckedCreateWithoutRequestsInput>
  where?: Prisma.workflow_stepsWhereInput
}

export type workflow_stepsUpdateToOneWithWhereWithoutRequestsInput = {
  where?: Prisma.workflow_stepsWhereInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRequestsInput, Prisma.workflow_stepsUncheckedUpdateWithoutRequestsInput>
}

export type workflow_stepsUpdateWithoutRequestsInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUpdateManyWithoutWorkflow_stepsNestedInput
  roles?: Prisma.rolesUpdateOneWithoutWorkflow_stepsNestedInput
  workflows?: Prisma.workflowsUpdateOneWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateWithoutRequestsInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsCreateWithoutRolesInput = {
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsCreateNestedManyWithoutWorkflow_stepsInput
  workflows?: Prisma.workflowsCreateNestedOneWithoutWorkflow_stepsInput
}

export type workflow_stepsUncheckedCreateWithoutRolesInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
}

export type workflow_stepsCreateOrConnectWithoutRolesInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput>
}

export type workflow_stepsCreateManyRolesInputEnvelope = {
  data: Prisma.workflow_stepsCreateManyRolesInput | Prisma.workflow_stepsCreateManyRolesInput[]
  skipDuplicates?: boolean
}

export type workflow_stepsUpsertWithWhereUniqueWithoutRolesInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  update: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRolesInput, Prisma.workflow_stepsUncheckedUpdateWithoutRolesInput>
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutRolesInput, Prisma.workflow_stepsUncheckedCreateWithoutRolesInput>
}

export type workflow_stepsUpdateWithWhereUniqueWithoutRolesInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutRolesInput, Prisma.workflow_stepsUncheckedUpdateWithoutRolesInput>
}

export type workflow_stepsUpdateManyWithWhereWithoutRolesInput = {
  where: Prisma.workflow_stepsScalarWhereInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateManyMutationInput, Prisma.workflow_stepsUncheckedUpdateManyWithoutRolesInput>
}

export type workflow_stepsScalarWhereInput = {
  AND?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
  OR?: Prisma.workflow_stepsScalarWhereInput[]
  NOT?: Prisma.workflow_stepsScalarWhereInput | Prisma.workflow_stepsScalarWhereInput[]
  step_id?: Prisma.IntFilter<"workflow_steps"> | number
  workflow_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  order?: Prisma.IntFilter<"workflow_steps"> | number
  name?: Prisma.StringNullableFilter<"workflow_steps"> | string | null
  approver_role_id?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  sla_hours?: Prisma.IntNullableFilter<"workflow_steps"> | number | null
  is_final?: Prisma.BoolNullableFilter<"workflow_steps"> | boolean | null
}

export type workflow_stepsCreateWithoutWorkflowsInput = {
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsCreateNestedManyWithoutWorkflow_stepsInput
  roles?: Prisma.rolesCreateNestedOneWithoutWorkflow_stepsInput
}

export type workflow_stepsUncheckedCreateWithoutWorkflowsInput = {
  step_id?: number
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
  request_actions?: Prisma.request_actionsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
  requests?: Prisma.requestsUncheckedCreateNestedManyWithoutWorkflow_stepsInput
}

export type workflow_stepsCreateOrConnectWithoutWorkflowsInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput>
}

export type workflow_stepsCreateManyWorkflowsInputEnvelope = {
  data: Prisma.workflow_stepsCreateManyWorkflowsInput | Prisma.workflow_stepsCreateManyWorkflowsInput[]
  skipDuplicates?: boolean
}

export type workflow_stepsUpsertWithWhereUniqueWithoutWorkflowsInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  update: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedUpdateWithoutWorkflowsInput>
  create: Prisma.XOR<Prisma.workflow_stepsCreateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedCreateWithoutWorkflowsInput>
}

export type workflow_stepsUpdateWithWhereUniqueWithoutWorkflowsInput = {
  where: Prisma.workflow_stepsWhereUniqueInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateWithoutWorkflowsInput, Prisma.workflow_stepsUncheckedUpdateWithoutWorkflowsInput>
}

export type workflow_stepsUpdateManyWithWhereWithoutWorkflowsInput = {
  where: Prisma.workflow_stepsScalarWhereInput
  data: Prisma.XOR<Prisma.workflow_stepsUpdateManyMutationInput, Prisma.workflow_stepsUncheckedUpdateManyWithoutWorkflowsInput>
}

export type workflow_stepsCreateManyRolesInput = {
  step_id?: number
  workflow_id?: number | null
  order: number
  name?: string | null
  sla_hours?: number | null
  is_final?: boolean | null
}

export type workflow_stepsUpdateWithoutRolesInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUpdateManyWithoutWorkflow_stepsNestedInput
  workflows?: Prisma.workflowsUpdateOneWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateWithoutRolesInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateManyWithoutRolesInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  workflow_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type workflow_stepsCreateManyWorkflowsInput = {
  step_id?: number
  order: number
  name?: string | null
  approver_role_id?: number | null
  sla_hours?: number | null
  is_final?: boolean | null
}

export type workflow_stepsUpdateWithoutWorkflowsInput = {
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUpdateManyWithoutWorkflow_stepsNestedInput
  roles?: Prisma.rolesUpdateOneWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateWithoutWorkflowsInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  request_actions?: Prisma.request_actionsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
  requests?: Prisma.requestsUncheckedUpdateManyWithoutWorkflow_stepsNestedInput
}

export type workflow_stepsUncheckedUpdateManyWithoutWorkflowsInput = {
  step_id?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  approver_role_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sla_hours?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_final?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}


/**
 * Count Type Workflow_stepsCountOutputType
 */

export type Workflow_stepsCountOutputType = {
  request_actions: number
  requests: number
}

export type Workflow_stepsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request_actions?: boolean | Workflow_stepsCountOutputTypeCountRequest_actionsArgs
  requests?: boolean | Workflow_stepsCountOutputTypeCountRequestsArgs
}

/**
 * Workflow_stepsCountOutputType without action
 */
export type Workflow_stepsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow_stepsCountOutputType
   */
  select?: Prisma.Workflow_stepsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Workflow_stepsCountOutputType without action
 */
export type Workflow_stepsCountOutputTypeCountRequest_actionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.request_actionsWhereInput
}

/**
 * Workflow_stepsCountOutputType without action
 */
export type Workflow_stepsCountOutputTypeCountRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.requestsWhereInput
}


export type workflow_stepsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  step_id?: boolean
  workflow_id?: boolean
  order?: boolean
  name?: boolean
  approver_role_id?: boolean
  sla_hours?: boolean
  is_final?: boolean
  request_actions?: boolean | Prisma.workflow_steps$request_actionsArgs<ExtArgs>
  requests?: boolean | Prisma.workflow_steps$requestsArgs<ExtArgs>
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
  _count?: boolean | Prisma.Workflow_stepsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflow_steps"]>

export type workflow_stepsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  step_id?: boolean
  workflow_id?: boolean
  order?: boolean
  name?: boolean
  approver_role_id?: boolean
  sla_hours?: boolean
  is_final?: boolean
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
}, ExtArgs["result"]["workflow_steps"]>

export type workflow_stepsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  step_id?: boolean
  workflow_id?: boolean
  order?: boolean
  name?: boolean
  approver_role_id?: boolean
  sla_hours?: boolean
  is_final?: boolean
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
}, ExtArgs["result"]["workflow_steps"]>

export type workflow_stepsSelectScalar = {
  step_id?: boolean
  workflow_id?: boolean
  order?: boolean
  name?: boolean
  approver_role_id?: boolean
  sla_hours?: boolean
  is_final?: boolean
}

export type workflow_stepsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"step_id" | "workflow_id" | "order" | "name" | "approver_role_id" | "sla_hours" | "is_final", ExtArgs["result"]["workflow_steps"]>
export type workflow_stepsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  request_actions?: boolean | Prisma.workflow_steps$request_actionsArgs<ExtArgs>
  requests?: boolean | Prisma.workflow_steps$requestsArgs<ExtArgs>
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
  _count?: boolean | Prisma.Workflow_stepsCountOutputTypeDefaultArgs<ExtArgs>
}
export type workflow_stepsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
}
export type workflow_stepsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roles?: boolean | Prisma.workflow_steps$rolesArgs<ExtArgs>
  workflows?: boolean | Prisma.workflow_steps$workflowsArgs<ExtArgs>
}

export type $workflow_stepsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "workflow_steps"
  objects: {
    request_actions: Prisma.$request_actionsPayload<ExtArgs>[]
    requests: Prisma.$requestsPayload<ExtArgs>[]
    roles: Prisma.$rolesPayload<ExtArgs> | null
    workflows: Prisma.$workflowsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    step_id: number
    workflow_id: number | null
    order: number
    name: string | null
    approver_role_id: number | null
    sla_hours: number | null
    is_final: boolean | null
  }, ExtArgs["result"]["workflow_steps"]>
  composites: {}
}

export type workflow_stepsGetPayload<S extends boolean | null | undefined | workflow_stepsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload, S>

export type workflow_stepsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<workflow_stepsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Workflow_stepsCountAggregateInputType | true
  }

export interface workflow_stepsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['workflow_steps'], meta: { name: 'workflow_steps' } }
  /**
   * Find zero or one Workflow_steps that matches the filter.
   * @param {workflow_stepsFindUniqueArgs} args - Arguments to find a Workflow_steps
   * @example
   * // Get one Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends workflow_stepsFindUniqueArgs>(args: Prisma.SelectSubset<T, workflow_stepsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Workflow_steps that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {workflow_stepsFindUniqueOrThrowArgs} args - Arguments to find a Workflow_steps
   * @example
   * // Get one Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends workflow_stepsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, workflow_stepsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workflow_steps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsFindFirstArgs} args - Arguments to find a Workflow_steps
   * @example
   * // Get one Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends workflow_stepsFindFirstArgs>(args?: Prisma.SelectSubset<T, workflow_stepsFindFirstArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workflow_steps that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsFindFirstOrThrowArgs} args - Arguments to find a Workflow_steps
   * @example
   * // Get one Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends workflow_stepsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, workflow_stepsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Workflow_steps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findMany()
   * 
   * // Get first 10 Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.findMany({ take: 10 })
   * 
   * // Only select the `step_id`
   * const workflow_stepsWithStep_idOnly = await prisma.workflow_steps.findMany({ select: { step_id: true } })
   * 
   */
  findMany<T extends workflow_stepsFindManyArgs>(args?: Prisma.SelectSubset<T, workflow_stepsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Workflow_steps.
   * @param {workflow_stepsCreateArgs} args - Arguments to create a Workflow_steps.
   * @example
   * // Create one Workflow_steps
   * const Workflow_steps = await prisma.workflow_steps.create({
   *   data: {
   *     // ... data to create a Workflow_steps
   *   }
   * })
   * 
   */
  create<T extends workflow_stepsCreateArgs>(args: Prisma.SelectSubset<T, workflow_stepsCreateArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Workflow_steps.
   * @param {workflow_stepsCreateManyArgs} args - Arguments to create many Workflow_steps.
   * @example
   * // Create many Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends workflow_stepsCreateManyArgs>(args?: Prisma.SelectSubset<T, workflow_stepsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Workflow_steps and returns the data saved in the database.
   * @param {workflow_stepsCreateManyAndReturnArgs} args - Arguments to create many Workflow_steps.
   * @example
   * // Create many Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Workflow_steps and only return the `step_id`
   * const workflow_stepsWithStep_idOnly = await prisma.workflow_steps.createManyAndReturn({
   *   select: { step_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends workflow_stepsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, workflow_stepsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Workflow_steps.
   * @param {workflow_stepsDeleteArgs} args - Arguments to delete one Workflow_steps.
   * @example
   * // Delete one Workflow_steps
   * const Workflow_steps = await prisma.workflow_steps.delete({
   *   where: {
   *     // ... filter to delete one Workflow_steps
   *   }
   * })
   * 
   */
  delete<T extends workflow_stepsDeleteArgs>(args: Prisma.SelectSubset<T, workflow_stepsDeleteArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Workflow_steps.
   * @param {workflow_stepsUpdateArgs} args - Arguments to update one Workflow_steps.
   * @example
   * // Update one Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends workflow_stepsUpdateArgs>(args: Prisma.SelectSubset<T, workflow_stepsUpdateArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Workflow_steps.
   * @param {workflow_stepsDeleteManyArgs} args - Arguments to filter Workflow_steps to delete.
   * @example
   * // Delete a few Workflow_steps
   * const { count } = await prisma.workflow_steps.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends workflow_stepsDeleteManyArgs>(args?: Prisma.SelectSubset<T, workflow_stepsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workflow_steps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends workflow_stepsUpdateManyArgs>(args: Prisma.SelectSubset<T, workflow_stepsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workflow_steps and returns the data updated in the database.
   * @param {workflow_stepsUpdateManyAndReturnArgs} args - Arguments to update many Workflow_steps.
   * @example
   * // Update many Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Workflow_steps and only return the `step_id`
   * const workflow_stepsWithStep_idOnly = await prisma.workflow_steps.updateManyAndReturn({
   *   select: { step_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends workflow_stepsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, workflow_stepsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Workflow_steps.
   * @param {workflow_stepsUpsertArgs} args - Arguments to update or create a Workflow_steps.
   * @example
   * // Update or create a Workflow_steps
   * const workflow_steps = await prisma.workflow_steps.upsert({
   *   create: {
   *     // ... data to create a Workflow_steps
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Workflow_steps we want to update
   *   }
   * })
   */
  upsert<T extends workflow_stepsUpsertArgs>(args: Prisma.SelectSubset<T, workflow_stepsUpsertArgs<ExtArgs>>): Prisma.Prisma__workflow_stepsClient<runtime.Types.Result.GetResult<Prisma.$workflow_stepsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Workflow_steps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsCountArgs} args - Arguments to filter Workflow_steps to count.
   * @example
   * // Count the number of Workflow_steps
   * const count = await prisma.workflow_steps.count({
   *   where: {
   *     // ... the filter for the Workflow_steps we want to count
   *   }
   * })
  **/
  count<T extends workflow_stepsCountArgs>(
    args?: Prisma.Subset<T, workflow_stepsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Workflow_stepsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Workflow_steps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Workflow_stepsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Workflow_stepsAggregateArgs>(args: Prisma.Subset<T, Workflow_stepsAggregateArgs>): Prisma.PrismaPromise<GetWorkflow_stepsAggregateType<T>>

  /**
   * Group by Workflow_steps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {workflow_stepsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends workflow_stepsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: workflow_stepsGroupByArgs['orderBy'] }
      : { orderBy?: workflow_stepsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, workflow_stepsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflow_stepsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the workflow_steps model
 */
readonly fields: workflow_stepsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for workflow_steps.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__workflow_stepsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  request_actions<T extends Prisma.workflow_steps$request_actionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.workflow_steps$request_actionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$request_actionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  requests<T extends Prisma.workflow_steps$requestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.workflow_steps$requestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$requestsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  roles<T extends Prisma.workflow_steps$rolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.workflow_steps$rolesArgs<ExtArgs>>): Prisma.Prisma__rolesClient<runtime.Types.Result.GetResult<Prisma.$rolesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  workflows<T extends Prisma.workflow_steps$workflowsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.workflow_steps$workflowsArgs<ExtArgs>>): Prisma.Prisma__workflowsClient<runtime.Types.Result.GetResult<Prisma.$workflowsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the workflow_steps model
 */
export interface workflow_stepsFieldRefs {
  readonly step_id: Prisma.FieldRef<"workflow_steps", 'Int'>
  readonly workflow_id: Prisma.FieldRef<"workflow_steps", 'Int'>
  readonly order: Prisma.FieldRef<"workflow_steps", 'Int'>
  readonly name: Prisma.FieldRef<"workflow_steps", 'String'>
  readonly approver_role_id: Prisma.FieldRef<"workflow_steps", 'Int'>
  readonly sla_hours: Prisma.FieldRef<"workflow_steps", 'Int'>
  readonly is_final: Prisma.FieldRef<"workflow_steps", 'Boolean'>
}
    

// Custom InputTypes
/**
 * workflow_steps findUnique
 */
export type workflow_stepsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter, which workflow_steps to fetch.
   */
  where: Prisma.workflow_stepsWhereUniqueInput
}

/**
 * workflow_steps findUniqueOrThrow
 */
export type workflow_stepsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter, which workflow_steps to fetch.
   */
  where: Prisma.workflow_stepsWhereUniqueInput
}

/**
 * workflow_steps findFirst
 */
export type workflow_stepsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter, which workflow_steps to fetch.
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of workflow_steps to fetch.
   */
  orderBy?: Prisma.workflow_stepsOrderByWithRelationInput | Prisma.workflow_stepsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for workflow_steps.
   */
  cursor?: Prisma.workflow_stepsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` workflow_steps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` workflow_steps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of workflow_steps.
   */
  distinct?: Prisma.Workflow_stepsScalarFieldEnum | Prisma.Workflow_stepsScalarFieldEnum[]
}

/**
 * workflow_steps findFirstOrThrow
 */
export type workflow_stepsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter, which workflow_steps to fetch.
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of workflow_steps to fetch.
   */
  orderBy?: Prisma.workflow_stepsOrderByWithRelationInput | Prisma.workflow_stepsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for workflow_steps.
   */
  cursor?: Prisma.workflow_stepsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` workflow_steps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` workflow_steps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of workflow_steps.
   */
  distinct?: Prisma.Workflow_stepsScalarFieldEnum | Prisma.Workflow_stepsScalarFieldEnum[]
}

/**
 * workflow_steps findMany
 */
export type workflow_stepsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter, which workflow_steps to fetch.
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of workflow_steps to fetch.
   */
  orderBy?: Prisma.workflow_stepsOrderByWithRelationInput | Prisma.workflow_stepsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing workflow_steps.
   */
  cursor?: Prisma.workflow_stepsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` workflow_steps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` workflow_steps.
   */
  skip?: number
  distinct?: Prisma.Workflow_stepsScalarFieldEnum | Prisma.Workflow_stepsScalarFieldEnum[]
}

/**
 * workflow_steps create
 */
export type workflow_stepsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * The data needed to create a workflow_steps.
   */
  data: Prisma.XOR<Prisma.workflow_stepsCreateInput, Prisma.workflow_stepsUncheckedCreateInput>
}

/**
 * workflow_steps createMany
 */
export type workflow_stepsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many workflow_steps.
   */
  data: Prisma.workflow_stepsCreateManyInput | Prisma.workflow_stepsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * workflow_steps createManyAndReturn
 */
export type workflow_stepsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * The data used to create many workflow_steps.
   */
  data: Prisma.workflow_stepsCreateManyInput | Prisma.workflow_stepsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * workflow_steps update
 */
export type workflow_stepsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * The data needed to update a workflow_steps.
   */
  data: Prisma.XOR<Prisma.workflow_stepsUpdateInput, Prisma.workflow_stepsUncheckedUpdateInput>
  /**
   * Choose, which workflow_steps to update.
   */
  where: Prisma.workflow_stepsWhereUniqueInput
}

/**
 * workflow_steps updateMany
 */
export type workflow_stepsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update workflow_steps.
   */
  data: Prisma.XOR<Prisma.workflow_stepsUpdateManyMutationInput, Prisma.workflow_stepsUncheckedUpdateManyInput>
  /**
   * Filter which workflow_steps to update
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * Limit how many workflow_steps to update.
   */
  limit?: number
}

/**
 * workflow_steps updateManyAndReturn
 */
export type workflow_stepsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * The data used to update workflow_steps.
   */
  data: Prisma.XOR<Prisma.workflow_stepsUpdateManyMutationInput, Prisma.workflow_stepsUncheckedUpdateManyInput>
  /**
   * Filter which workflow_steps to update
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * Limit how many workflow_steps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * workflow_steps upsert
 */
export type workflow_stepsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * The filter to search for the workflow_steps to update in case it exists.
   */
  where: Prisma.workflow_stepsWhereUniqueInput
  /**
   * In case the workflow_steps found by the `where` argument doesn't exist, create a new workflow_steps with this data.
   */
  create: Prisma.XOR<Prisma.workflow_stepsCreateInput, Prisma.workflow_stepsUncheckedCreateInput>
  /**
   * In case the workflow_steps was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.workflow_stepsUpdateInput, Prisma.workflow_stepsUncheckedUpdateInput>
}

/**
 * workflow_steps delete
 */
export type workflow_stepsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
  /**
   * Filter which workflow_steps to delete.
   */
  where: Prisma.workflow_stepsWhereUniqueInput
}

/**
 * workflow_steps deleteMany
 */
export type workflow_stepsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which workflow_steps to delete
   */
  where?: Prisma.workflow_stepsWhereInput
  /**
   * Limit how many workflow_steps to delete.
   */
  limit?: number
}

/**
 * workflow_steps.request_actions
 */
export type workflow_steps$request_actionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the request_actions
   */
  select?: Prisma.request_actionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the request_actions
   */
  omit?: Prisma.request_actionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.request_actionsInclude<ExtArgs> | null
  where?: Prisma.request_actionsWhereInput
  orderBy?: Prisma.request_actionsOrderByWithRelationInput | Prisma.request_actionsOrderByWithRelationInput[]
  cursor?: Prisma.request_actionsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Request_actionsScalarFieldEnum | Prisma.Request_actionsScalarFieldEnum[]
}

/**
 * workflow_steps.requests
 */
export type workflow_steps$requestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the requests
   */
  select?: Prisma.requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the requests
   */
  omit?: Prisma.requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.requestsInclude<ExtArgs> | null
  where?: Prisma.requestsWhereInput
  orderBy?: Prisma.requestsOrderByWithRelationInput | Prisma.requestsOrderByWithRelationInput[]
  cursor?: Prisma.requestsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RequestsScalarFieldEnum | Prisma.RequestsScalarFieldEnum[]
}

/**
 * workflow_steps.roles
 */
export type workflow_steps$rolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the roles
   */
  select?: Prisma.rolesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the roles
   */
  omit?: Prisma.rolesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.rolesInclude<ExtArgs> | null
  where?: Prisma.rolesWhereInput
}

/**
 * workflow_steps.workflows
 */
export type workflow_steps$workflowsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflows
   */
  select?: Prisma.workflowsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflows
   */
  omit?: Prisma.workflowsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflowsInclude<ExtArgs> | null
  where?: Prisma.workflowsWhereInput
}

/**
 * workflow_steps without action
 */
export type workflow_stepsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the workflow_steps
   */
  select?: Prisma.workflow_stepsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the workflow_steps
   */
  omit?: Prisma.workflow_stepsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.workflow_stepsInclude<ExtArgs> | null
}
